### ISSUE TITLE
Disable Zuul CI integration until service become stable

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-lint#1002]
##### Summary
Due the huge number of false failures reported Zuul CI since its introduction 8 months ago, I propose disabling Zuul integration for **ansible-lint** project until the deployment becomes stable.

##### Issue Type

- Feature Idea

##### Additional Information

Main reason for proposing this is because even if Zuul reporting is non-voting, it does confuse not only ocasional contributors but also cores. I find myself confused by random false X checks on pulls, pulls that indeed passed our active CI.

We can blame github UI for displaying red-X for PRs that had even one failed check that was not counted.

I still like Zuul CI and continue to contribute to it upstream but I see negative value of using current deployment for ansible-lint project. I wasted a countless number of hours trying to keep the linter zuul jobs green and in all cases it was an infrastructure issue: either a disk-image being updated or another chance unrelated to the project itself.

Also having zuul enabled does slow us down bringing the test run durations from ~5-7min to >30mins, as zuul is much slower than github-actions, in many cases jobs didn't even start on zuul when github actions ended.

I propose revisiting this in 6 months, hopefully the situation will be better.

**Comment by webknjaz** [comment]
Go for it

**Comment by awcrosby** [comment]
Agreed

**Comment by ssbarnea** [comment]
Done. We are zuul free now.
