### ISSUE TITLE
RFE: Add a (sub) section to show how to make a custom lint rule (python) package

### ISSUE THREAD

**Issue by ssato** [ansible/ansible-lint#1029]
##### SUMMARY

Its document provides a description how to create a custom rule class but doesn't provide info how to make a custom lint rule collection as a python package, IMHO.

- https://ansible-lint.readthedocs.io/en/latest/rules.html#creating-custom-rules

I guess that it would be very useful who create and distribute custom rules in their organizations.

##### ISSUE TYPE

- Documentation Report

##### OS / ENVIRONMENT

This is not depends on OS/Environment.

##### ADDITIONAL INFORMATION

I think some info like followings should be enough as a starting point.

- how to package: describe where the custom rules should be installed and packaged as usual python package using examples like followings.

  - setup.cfg example: https://github.com/ssato/ansible-lint-custom-rules/blob/master/setup.cfg#L43
  - dir layout example: https://github.com/ssato/ansible-lint-custom-rules/tree/master/rules

- how to test and CI: describe how to test custom rules and running CI tests using examples like followings.

  - tox.ini example: https://github.com/ssato/ansible-lint-custom-rules/blob/master/tox.ini#L17
  - test code example: https://github.com/ssato/ansible-lint-custom-rules/tree/master/tests
  - github actions configuration examples: https://github.com/ssato/ansible-lint-custom-rules/tree/master/.github/workflows

**Comment by ssbarnea** [comment]
Just yesterday I closed a 3 year old bug that was asking for this, mainly because nobody proposed a PR.
At this moment the linter can only load custom rules from a given file path. If you want plugins installable as python wherls, feel free to create a PR that uses pluggy to discover them.

**Comment by ssbarnea** [comment]
Just yesterday I closed a 3 year old bug that was asking for this, mainly because nobody proposed a PR.
At this moment the linter can only load custom rules from a given file path. If you want plugins installable as python wherls, feel free to create a PR that uses pluggy to discover them.

**Comment by ssbarnea** [comment]
Just yesterday I closed a 3 year old bug that was asking for this, mainly because nobody proposed a PR.
At this moment the linter can only load custom rules from a given file path. If you want plugins installable as python wherls, feel free to create a PR that uses pluggy to discover them.

**Comment by ssbarnea** [comment]
Just yesterday I closed a 3 year old bug that was asking for this, mainly because nobody proposed a PR.
At this moment the linter can only load custom rules from a given file path. If you want plugins installable as python wherls, feel free to create a PR that uses pluggy to discover them.

**Comment by ssbarnea** [comment]
Just yesterday I closed a 3 year old bug that was asking for this, mainly because nobody proposed a PR.
At this moment the linter can only load custom rules from a given file path. If you want plugins installable as python wherls, feel free to create a PR that uses pluggy to discover them.

**Comment by ssbarnea** [comment]
Just yesterday I closed a 3 year old bug that was asking for this, mainly because nobody proposed a PR.
At this moment the linter can only load custom rules from a given file path. If you want plugins installable as python wherls, feel free to create a PR that uses pluggy to discover them.

**Comment by ssbarnea** [comment]
Just yesterday I closed a 3 year old bug that was asking for this, mainly because nobody proposed a PR.
At this moment the linter can only load custom rules from a given file path. If you want plugins installable as python wherls, feel free to create a PR that uses pluggy to discover them.

**Comment by ssbarnea** [comment]
Just yesterday I closed a 3 year old bug that was asking for this, mainly because nobody proposed a PR.
At this moment the linter can only load custom rules from a given file path. If you want plugins installable as python wherls, feel free to create a PR that uses pluggy to discover them.

**Comment by ssbarnea** [comment]
Just yesterday I closed a 3 year old bug that was asking for this, mainly because nobody proposed a PR.
At this moment the linter can only load custom rules from a given file path. If you want plugins installable as python wherls, feel free to create a PR that uses pluggy to discover them.

**Comment by ssato** [comment]
I've just created the pr #1036 for this.

Because English is not my native language and it should need to be fixed and improved but it may become a start, I think.

> At this moment the linter can only load custom rules from a given file path. If you want plugins installable as python wherls, feel free to create a PR that uses pluggy to discover them.

We don't need such thing because ansbile-lint already can find and load custom rules from <default_rules_dir>/custom/*/ automatically and let the custom rules' developers know where to install their custom rules should be enough, I think.
