### ISSUE TITLE
Extend ansible-lint to work with Language Server Protocol and add completion

### ISSUE THREAD

**Issue by paulkitt** [ansible/ansible-lint#1056]
##### Summary
Extending ansible-lint to follow the [Language Server Protocol](https://langserver.org/) and add completion.
In most editors only syntax highlight is available and linting has be added separately via ansible-lint. Completion
is only available in the vscode extension.

It would be great to have a implementation for the Language Server Protocol to bring this features to many editors at once.

##### Issue Type

- Feature Idea

**Comment by ssbarnea** [comment]
@paulkitt I am aware of LSP but I did not see how this would fit a linter, I was seeing it more at the language level, for which this would require an Ansible implementation.

Do you have any examples of linters implementing it?

**Comment by paulkitt** [comment]
Ok then I will open this feature request in the general Ansible repository if its fits better there. While improving my work environment I just stumbled on LSP and due to bad editor integration of ansible an implementation of LSP with completion and diagnostics would be such an upgrade.

I dont have an example of linters implementing lsp.

**Comment by paulkitt** [comment]
Opened an [issue](https://github.com/ansible/ansible/issues/71757) an the main Ansible repository. This issue couldn't be closed.
