### ISSUE TITLE
Can I go over directory instead of playbook?

### ISSUE THREAD

**Issue by yfried** [ansible/ansible-lint#112]
Usage calls for a specific playbook. How can I go over all playbooks in dir instead?

**Comment by willthames** [comment]
It will now go over a role directory. The problem with a playbook directory is that not everything in it might be a playbook (e.g. we tend to store rolesfiles in the same directory). 

It might well be easier to use find and xargs, but implementations that include `--exclude` filters will be considered (probably best to suggest what an implementation might look like before implementing it though)

**Comment by ssbarnea** [comment]
If run from bash, doing something like `ansible-linter *.yml` should work, right?

**Comment by willthames** [comment]
@ssbarnea apart from rolesfile.yml, sure.

**Comment by ssbarnea** [comment]
I don't like that the fact that doing this generates lots of new lines which are not desired. It seems that ansible-lint adds an extra empty line to the output.

**Comment by willthames** [comment]
That sounds like a separate bug.

**Comment by nickpack** [comment]
`find . -type f -name "*.yml" -exec /usr/local/bin/ansible-lint -p -q {} ` Works well enough usually - not sure this actually needs fixing.

**Comment by ssbarnea** [comment]
Obsolete, the linter can already auto-detect repository layout or scan folders. It is no longer needed to use `find`.
