### ISSUE TITLE
progressive mode switches to incompatible cwd between runs

### ISSUE THREAD

**Issue by pikrzysztof** [ansible/ansible-lint#1251]
Imagine a scenario:
```
# cd myrepo
# ls -a
.
..
.git
ansible-stuff
other-stuff
# ls -a ansible-stuff
.
..
.ansible-lint
ansible.cfg
playbookone.yml
group_vars
host_vars
roles
```
When invoking `cd myrepo/ansible-stuff && ansible-lint --progressive`, the first run (for HEAD commit) will work fine, however the `_previous_revision` context manager completely ignores the fact that ansible-lint was invoked in some subdirectory of the git repo and will return an incompatible working directory (`myrepo/.cache/old-rev/myrepo` instead of `myrepo/.cache/old-rev/myrepo/ansible-stuff`).

Quoting current implementation for reference: 
```
def _previous_revision():
    """Create or update a temporary workdir containing the previous revision."""
    worktree_dir = ".cache/old-rev"
    revision = subprocess.run(
        ["git", "rev-parse", "HEAD^1"],
        check=True,
        universal_newlines=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        ).stdout
    p = pathlib.Path(worktree_dir)
    p.mkdir(parents=True, exist_ok=True)
    os.system(f"git worktree add -f {worktree_dir} 2>/dev/null")
    with cwd(worktree_dir):
        os.system(f"git checkout {revision}")
        yield
```

**Comment by ssbarnea** [comment]
Progressive mode was introduced as possible workaround that would ease adoption of the linter for their code repositories. It was never intended to be used on subdirectories, or partial runs.

As this is not really a documented or probable use case, unless someone raise a pull-request, I will endup closing it.
