### ISSUE TITLE
Empty meta yaml triggers "TypeError: argument of type 'NoneType' is not iterable"

### ISSUE THREAD

**Issue by brlin-tw** [ansible/ansible-lint#1703]
> Verify first that your issue is not already reported on GitHub

Similar to #1021 but the error message is "iterable" instead of "subscriptable"

> Also test if the latest release and main branch are affected too

Successfully reproduced on 5.1.2, ~~not sure how to test the main branch using pipx installation, though~~[and the current main branch](https://github.com/ansible-community/ansible-lint/issues/1703#issuecomment-901659128)

##### Summary

Supplying an empty meta/main.yml triggers a TypeError crash, refer the reproduce instructions for example.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
$ ansible --version
ansible [core 2.11.4] 
  config file = /home/brlin/__REDACTED__/ansible.cfg
  configured module search path = ['/home/brlin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/brlin/.local/pipx/venvs/ansible/lib/python3.9/site-packages/ansible
  ansible collection location = /home/brlin/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/brlin/.local/bin/ansible
  python version = 3.9.5 (default, May 11 2021, 08:20:37) [GCC 10.3.0]
  jinja version = 3.0.1
  libyaml = True

$ ansible-lint --version
ansible-lint 5.1.2 using ansible 2.11.4
```

- ansible installation method: one of source, pip, OS package: pipx (based on pip)
- ansible-lint installation method: one of source, pip, OS package: pipx (based on pip)

##### OS / ENVIRONMENT

Ubuntu 21.04  
Python 3.9.5

##### STEPS TO REPRODUCE

```console
$ git clone https://github.com/Lin-Buo-Ren/ansible-lint-bug-repro-empty-meta.git
$ cd ansible-lint-bug-repro-empty-meta
$ ansible-lint
```

##### Desired Behaviour

Program not crashed, possibly giving linting errors regarding the improper meta file

##### Actual Behaviour

```python-traceback
$ ansible-lint
Traceback (most recent call last):
  File "/home/brlin/.local/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
  File "/home/brlin/.local/pipx/venvs/ansible-lint/lib/python3.9/site-packages/ansiblelint/__main__.py", line 299, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
  File "/home/brlin/.local/pipx/venvs/ansible-lint/lib/python3.9/site-packages/ansiblelint/__main__.py", line 206, in main
    prepare_environment()
  File "/home/brlin/.local/pipx/venvs/ansible-lint/lib/python3.9/site-packages/ansiblelint/prerun.py", line 211, in prepare_environment
    _install_galaxy_role()
  File "/home/brlin/.local/pipx/venvs/ansible-lint/lib/python3.9/site-packages/ansiblelint/prerun.py", line 253, in _install_galaxy_role
    if 'galaxy_info' not in yaml:
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by Lin-Buo-Ren** [comment]
I found out that the issue is NOT reproduced in v4.3.7.

**Comment by Lin-Buo-Ren** [comment]
I can successfully reproduce this issue on revision 629caa7 on the main branch via following the pipx's [Running from Source Control](https://pypa.github.io/pipx/#running-from-source-control) instruction:

```output
$ pipx run --spec git+https://github.com/ansible-community/ansible-lint.git@main ansible-lint
⚠️  ansible-lint is already on your PATH and installed at /home/brlin/.local/bin/ansible-lint. Downloading and running
    anyway.
Traceback (most recent call last):
  File "/home/brlin/.local/pipx/.cache/b019cd727866d20/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
  File "/home/brlin/.local/pipx/.cache/b019cd727866d20/lib/python3.9/site-packages/ansiblelint/__main__.py", line 299, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
  File "/home/brlin/.local/pipx/.cache/b019cd727866d20/lib/python3.9/site-packages/ansiblelint/__main__.py", line 206, in main
    prepare_environment()
  File "/home/brlin/.local/pipx/.cache/b019cd727866d20/lib/python3.9/site-packages/ansiblelint/prerun.py", line 211, in prepare_environment
    _install_galaxy_role()
  File "/home/brlin/.local/pipx/.cache/b019cd727866d20/lib/python3.9/site-packages/ansiblelint/prerun.py", line 253, in _install_galaxy_role
    if 'galaxy_info' not in yaml:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by webknjaz** [comment]
According to the source code, `yaml_from_file("meta/main.yml")` returns `None` in your case, here https://github.com/ansible-community/ansible-lint/blob/629caa7/src/ansiblelint/prerun.py#L252.
Looking at, https://github.com/ansible-community/ansible-lint/blob/629caa7/src/ansiblelint/loaders.py#L9-L10 I assumed that `meta/main.yml` exists on disk in your checked role but *is empty*.

I've just verified that `yaml.load()` returns `None` for empty documents:
```pycon
$ ipython
Python 3.9.0 (default, Oct 26 2020, 13:08:59)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import io

In [2]: import yaml

In [3]: yaml.load(io.BytesIO(b''), Loader=yaml.FullLoader) is None
Out[3]: True
```

Action items:
- Don't error out on invalid meta files
- Have a rule reporting this problem

Workaround: don't have an empty `meta/main.yml` in your project.

**Comment by Lin-Buo-Ren** [comment]
Thanks for the heads-up!

> Workaround: don't have an empty meta/main.yml in your project.

The actual meta/main.yml that triggers the issue is:

```yaml
# 此 Ansible 角色所依賴的 Ansible 角色
# https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#using-meta-main-yml
#dependencies:
  #- role: common
    #vars:
      #some_parameter: 3
  #- role: apache
    #vars:
      #apache_port: 80
  #- role: postgres
    #vars:
      #dbname: blarg
      #other_parameter: 12
```

which is a commented-out placeholder for fast incorporating the file, it seems that Ansible is totally fine with it.

**Comment by ganeshrn** [comment]
Blocked by #1666

**Comment by webknjaz** [comment]
@Lin-Buo-Ren if you're up to it, feel free to send us a PR reproducing this problem as per https://pganssle-talks.github.io/xfail-lightning/.
