### ISSUE TITLE
Option to limit scope of role linting

### ISSUE THREAD

**Issue by azenk** [ansible/ansible-lint#186]
# Issue Type
- Feature request
# Desired Behaviour

Currently, if executing ansible-lint from a precommit hook in a role, the only option is to lint all of the files, including those that have not changed.  Ideally there would be some way of saying "lint only these files within the role." 

Maybe a --limit or --include flag that would mirror the --exclude flag?  Alternatively a flag to set the base directory for the role, and then linting the files listed as positional arguments could work, but that seems like it would be more difficult to implement, as well as breaking existing functionality.

**Comment by willthames** [comment]
I recommend using [ansible-review](https://github.com/willthames/ansible-review) for this kind of thing - it's exactly what it's designed for.

**Comment by willthames** [comment]
Pull requests welcome that implement this behaviour though.

**Comment by moomzni** [comment]
I've found that if you pass in the '--exclude=/' option it will limit linting to the individual file
