### ISSUE TITLE
Rule request: Disallow prompting in playbooks

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-lint#2036]
e.g. pause/prompt
e.g. vars_prompt

This better positions playbooks for unattended runs and use in CI pipelines.

**Comment by ziegenberg** [comment]
@cidrblock The [documentation states](https://docs.ansible.com/ansible/latest/user_guide/playbooks_prompts.html): 

> Prompts for individual `vars_prompt` variables will be skipped for any variable that is already defined through the command line `--extra-vars` option, or when running from a non-interactive session (such as cron or Ansible AWX).

Would you still want to discourage the use of`vars_promt`?

And what about `vars_prompt` that defines a `default`?
