### ISSUE TITLE
name[template]: If a  `{{ }}` is found in a task name, require it's presence at the end after a sentence explaining the task

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-lint#2037]
and that is has a meaningful name not `item`

This is ok:

`name: "Start the requested service. {{ serivce_name }}"`

This should not be:

`name: "Enable {{ item.1 }}"`

**Comment by ssbarnea** [comment]
Implemented and released.

**Comment by williamhanseneric** [comment]
Disagree with this being an area that the linter needs to be concerned with... unless there is a real problem with the implementation, doing things like this inline in an intelligent way is cleaner and better... the linter is too opinionated.  

I want the linter to respond when something is not going to be supported in the future, or would lead to real usability issues.  Having this show up in the "basic" profile is not the way IMHO.

- name: Wait up to "{{ cli_conn_timeout }}" seconds for a machine connection before fact collection
        
- name: "Retrieve stdout from {{ ansible_controller_tower_name }} for {{ tower_job_id }} on errors"
