### ISSUE TITLE
no-changelog: check_collection_changelog

### ISSUE THREAD

**Issue by thedoubl3j** [ansible/ansible-lint#2101]
check the collection structure to confirm if there is a changelog file present at the root of the directory. 

rule should be optional and only enabled at users discretion. Error level should be Warn/Info (0)

based off of code found [here ](https://github.com/ansible/galaxy-importer/blob/master/galaxy_importer/loaders/collection.py#L119)

**Comment by thedoubl3j** [comment]
Context: being opened and tracked to be added to a specific profile for certification/galaxy-importer checks

**Comment by alisonlhart** [comment]
PE will be working on this one as well @ssbarnea
