### ISSUE TITLE
meta-unsupported-ansible: requires_ansible key 

### ISSUE THREAD

**Issue by thedoubl3j** [ansible/ansible-lint#2102]
affirm that the `requires_ansible:` key in the meta/runtime.yml file has a value within current supported versions of ansible-core

rule should be optional and only enabled at users discretion. Error level should be fatal (1) as galaxy-importer will disallow the import if not present currently. 

based off of code found [here](https://github.com/ansible/galaxy-importer/blob/master/galaxy_importer/loaders/runtime_file.py#L46)

similar context to #2101

**Comment by alisonlhart** [comment]
Volunteering to work on this one.
