### ISSUE TITLE
Fix support for block tasks in unnamed-task rule

### ISSUE THREAD

**Issue by cognifloyd** [ansible/ansible-lint#2104]
##### Summary

This is a follow-up for #1895 + #2031.

The `unnamed-task` rule does not detect block/rescue/always tasks that are missing `name:`.

In #2031, @nishipy fixed `matchtask()` so that it stops excluding block tasks. But several tests expect `unnamed-task` to skip over block tasks, so #2031 added `not is_nested_task(task)` to preserve the old (wrong) behavior.

At least these tests will need to be adjusted based on https://github.com/ansible/ansible-lint/pull/2031#discussion_r856859577:
- `test_no_same_owner_rule()`
- `test_included_tasks()`
- `test_runner_exclude_globs()`

##### Issue Type

- Bug Report

**Comment by nishipy** [comment]
Hi,
Can I work on this remaining issue?

**Comment by cognifloyd** [comment]
Yes please!

**Comment by nishipy** [comment]
Thanks!
