### ISSUE TITLE
Refactor rules to avoid re-inventing matchtasks()

### ISSUE THREAD

**Issue by cognifloyd** [ansible/ansible-lint#2105]
##### Summary

Some tasks avoided using `matchtask()` because, before #2031, block tasks were excluded. Now that block tasks are included, and they are included in a more robust manner than the rule-specific methods, those rules should be refactored to just use `matchtask()`.

Another reason to make sure that rules are using the standard `matchtask()` wherever possible is for the up-coming rule transforms feature (part of `--write`). The `matchtasks()` method (which calls `matchtask()`) enriches any returned match errors with metadata that facilitates finding/fixing the issue in rule transforms.

Here is where the parsed+normalized task gets attached to the MatchError:
https://github.com/ansible/ansible-lint/blob/f9ad8ea39705850b7753e4cb13c3cc7c82f176f8/src/ansiblelint/rules/__init__.py#L177
And here is where `create_matcherror()` adds info about how the match was identified (yaml vs play vs task):
https://github.com/ansible/ansible-lint/blob/f9ad8ea39705850b7753e4cb13c3cc7c82f176f8/src/ansiblelint/rules/__init__.py#L106-L107

These are the rules that need to be adjusted:

- [x] `no-loop-var-prefix`
    - currently uses `matchplay()` with custom match methods: `handle_play()`, `handle_tasks()`, `handle_task()`.
    - unlike the standard `match*()` methodds, the custom `block` detection in this rule is incomplete: it only descends into `block`, not `rescue` or `always`.
    - the `handle_*()` and `matchplay()` methods should be condensed into a single `matchtask()`.

- [x] `no-same-owner`
    - currently uses `matchplay()` with custom match methods: `handle_play()`, `handle_playlist()`, `handle_task()`.
    - like `no-loop-var-prefix` this also misses `rescue` and `always`.
    - the `handle_*()` and `matchplay()` methods should be condensed into a single `matchtask()` (`handle_unarchive()` and `handle_synchronize()` would probably stay as they are)

- [ ] `partial-become`
    - uses `matchplay()` with custom logic to search through the yaml for tasks.
    - actually does handle `block`, `rescue`, and `always`.
    - implementing a rule transform for this will be more difficult because it does not re-use the standard methods that also enrich matches with additional info.
    - `matchplay()` should only look at plays, not tasks.
    - `matchtask()` should handle tasks separately.

- [x] `deprecated-local-action`
    - uses `match()` to look at each line
    - can get false positives in comments or strings
    - does not benefit from any of the additional info that gets added by other standard methods

##### Issue Type

- Bug Report

**Comment by nishipy** [comment]
Hi, Thanks for summarizing the requirements. Can I work on this remaining issue?

**Comment by cognifloyd** [comment]
Yes please! :smile:

**Comment by nishipy** [comment]
Sorry for being not familiar with `no-loop-var-prefix`. I did some tests (I couldn't find test code) for it and saw it returns the following result for [this sample role](https://github.com/nishipy/ansible-playbooks/tree/main/roles/role_with_loop_var/tasks). 
I'm not sure but I think the 1st one might be an unexpected violation. What do you think? In `inner.yml`, the variable `item` has no prefix but won't be used with `loop_var` in `main.yml` which includes `inner.yml`. 
```
$ ansible-lint ../ansible-playbooks/var_loop.yml 
WARNING  Overriding detected file kind 'yaml' with 'playbook' for given positional argument: ../ansible-playbooks/var_loop.yml
WARNING  Listing 3 violation(s) that are fatal
no-loop-var-prefix: Role loop_var should use configured prefix.
../ansible-playbooks/roles/role_with_loop_var/tasks/inner.yml:2

no-loop-var-prefix: Role loop_var should use configured prefix.
../ansible-playbooks/roles/role_with_loop_var/tasks/inner_no_prefix.yml:2

no-loop-var-prefix: Role loop_var should use configured prefix.
../ansible-playbooks/roles/role_with_loop_var/tasks/main.yml:10
```  

In addition, as described above, we have no test code for the rules `no-loop-var-prefix`, `no-same-owner`, and `partial-become` in `test/rules` dir. Should I add tests before refactoring them?

**Comment by nishipy** [comment]
I've found test codes for `no-same-owner` and `partial-become` in the following files.
- no-same-owner: testing on not `test/rules` dir but `rules/no_same_owner.py`
- partial-become: testing on `test/rule/test_become_user_without_become.py`

However, if I understand correctly there seems to be no testing for `no-loop-var-prefix` now. I will start to add it before refactoring.

**Comment by cognifloyd** [comment]
@nishipy yeah. the test organization is a bit confusing thanks to the long history of this project :)

Tests under `test/rules/` are older tests. They were unittest-style tests, but were converted to pytest-style recently in #1985 and #1986.
Tests embedded in the rule files (under `src/ansibellint/rules/`) are the newer pytest-style tests. As rules are fairly self-contained, including the tests in the same files facilitates development and simplifies figuring out where a rule's tests are.

So, I consider tests under `test/rules/` to be "legacy" (ish). I would love to see all the tests in `test/rules/` moved into / embedded in the appropriate rule file. Would you please move the tests for the rules you're touching so that they're embedded in the rules file?

Thanks!

**Comment by nishipy** [comment]
Thank you for clarifying the background. I see.

> @nishipy Would you please move the tests for the rules you're touching so that they're embedded in the rules file?

Of course! Let me do that.

**Comment by ssbarnea** [comment]
@nishipy Just as note. Try to avoid big pull-requests, especially when it is possible to make smaller progressive changes. This will make it much easier to achieve these goals and avoid conflicts. I will do my best to speedup the reviews so we can move fast.

And thanks for helping!

**Comment by cognifloyd** [comment]
Hmm. That's true.

I think there are other issues about inherited parameters like #1894. Maybe we need some kind of generalized way to deal with inheritance.

Any help is appreciated. I'm getting closer to finishing the project I've been working on at work so I can get back to other things like ansible-lint.

**Comment by ssbarnea** [comment]
Inheritance of properties from parents is an known issue and we should sort it outside these refactorings, so matchtask will receive normalized data (inherited stuff already in). That should address the issue of having to look back.

Obviously that this will not work for people that define these values in hostvars or pass them using `-e` but that is ok, as those are unsafe and the code should already have safe defaults inside the same file.

**Comment by nishipy** [comment]
Oh, I didn’t know that. Let me see https://github.com/ansible/ansible-lint/issues/1894 later.

> so matchtask will receive normalized data (inherited stuff already in).

I'm sorry, but do you mean we can use the data returned from the following method?
https://github.com/ansible/ansible-lint/blob/main/src/ansiblelint/utils.py#L610-L618
