### ISSUE TITLE
Spaces between tasks in block not preserved when writing yaml

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-lint#2112]
Happen to notice this while borrowing some code from ansible-lint:

```
from ansiblelint.yaml_utils import FormattedYAML

yaml_str = """

- block:
   
    - debug:
        msg: "Hello World"

    - debug:
        msg: "Hello World"
    
    - debug:
        msg: "Hello World"
    
    - debug:
        msg: "Hello World"
"""

yaml = FormattedYAML()
obj = yaml.load(yaml_str)
output = yaml.dumps(obj)

print(output)


# ---
# - block:
#     - debug:
#         msg: Hello World

#     - debug:
#         msg: Hello World
#     - debug:
#         msg: Hello World
#     - debug:
#         msg: Hello World
```

**Comment by cidrblock** [comment]
I believe the issue is in `write_comment`, I was able to work around it with:

```
    if (
            pre
            and not value.strip()
            and not isinstance(
                self.event,
                (
                    ruamel.yaml.events.CollectionEndEvent,
                    ruamel.yaml.events.DocumentEndEvent,
                    ruamel.yaml.events.StreamEndEvent,
                    ruamel.yaml.events.MappingStartEvent, <-----
                ),
            )
        ):
```
but don't know the code well enough to know if this is the right fix or just hiding the issue

**Comment by ssbarnea** [comment]
I am not sure which are the current technical limitations but I would personally want to see one space added between each task. I know that this is a bit deliberate/custom rule for ansible tasks that might apply only to few specific sequences. Another one that might find it useful is github workflow action steps sequence, for the same reasons.

**Comment by cidrblock** [comment]
@ssbarnea Yes!  One blank line between each task would be a really nice default.  I think it makes for very readable task files.....

**Comment by shatakshiiii** [comment]
Closed by https://github.com/ansible/ansible-lint/pull/3641
