### ISSUE TITLE
disallowed-ignore[sanity]: disallow specific skips in ignore files

### ISSUE THREAD

**Issue by thedoubl3j** [ansible/ansible-lint#2121]
filter/read ignore file and compare against a static/hardcoded list of tests that are allowed to be skipped. 

example of allowed skip: `validate-modules:missing-gplv3-license` as AAP allows more than gpl licensing for collections

**Comment by ssbarnea** [comment]
We want to allow some rules to declare themselves unskippable when run in strict mode, strict mode is always use by validators.

**Comment by cidrblock** [comment]
The goal here is to look inside the ansible-test ignore file and ensure certain things are not being skipped e.g. this file: https://github.com/ansible-collections/cisco.nxos/blob/main/tests/sanity/ignore-2.10.txt

**Comment by cidrblock** [comment]
Related: https://github.com/ansible/galaxy-importer/blob/b7140d6b3b5e172553788ae9aaa7526f8ff49ea2/galaxy_importer/loaders/collection.py#L99

**Comment by MarkusTeufelberger** [comment]
This is really annoying if there are bugs within Ansible that concern sanity tests. Concretely in my case: https://github.com/ansible/ansible/issues/76612

The issue in ansible/ansible got closed by a bot, there still is an open PR (https://github.com/ansible/ansible/pull/79700) that's unreviewed for months (the bug has been reported for years now) and this new rule means I need to add some ignores (how do I do that actually?) for this rule to my ignore-files or globally ignore this rule completely until the bug in Ansible itself that requires the disallowed ignore is fixed and backported.

Please advise how to disable this check for single lines in a sanity ignore file.
