### ISSUE TITLE
no-name: (auto-fix) auto add name to set_fact if missing

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-lint#2130]
As seen in this PR: https://github.com/ansible-collections/cisco.nxos/pull/504/files

(was done with this hacky little cleanup script, in `def update_set_fact_name`)  https://gist.github.com/cidrblock/865826d5cfa2bd7d1ce028ffe9067a1b

**Comment by ssbarnea** [comment]
Closing as not planned as we would not be able to auto generate a logical name.
