### ISSUE TITLE
name-capital: All tasks should be named and start with a capital letter

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-lint#2169]
Starting to pull in possible rule ideas from the community of practice: https://github.com/redhat-cop/automation-good-practices/pull/64

The description of a task (the name key) should start with a capital letter, this will help with readability and help task files and playbook read more like documentation.

**Comment by ktdreyer** [comment]
Anyone have a good `sed` command that will globally fix this problem? It would be great to add this to the ansible-lint docs.

**Comment by ssbarnea** [comment]
@cognifloyd ^ that might be a good opportunity to add rewrite for this one.

I used code (vscode) search and replace in files with regex to fix them.

**Comment by bolinocroustibat** [comment]
I also express strong disagreement with this rule. A name referring to a role should not include capital letters. Capital letter are for complete sentences, not for labels.
