### ISSUE TITLE
size[block]: Limit the maximum block depth

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-lint#2173]
Starting to pull in possible rule ideas from the community of practice: https://github.com/redhat-cop/automation-good-practices/pull/64

Ofter, using an include within a block leads to more readable playbooks and task file vs. a deep block depth.

It might not be possible to check across files and I'm not sure lint tracks block state, but within a single file we should be able to limit it.

2 was suggested only as a starting point

**Comment by Ruchip16** [comment]
@ssbarnea I can try fixing this

**Comment by ssbarnea** [comment]
@Ruchip16 Any updates on it? Asking as I might do it myself if you don't have time.

**Comment by ajinkyau** [comment]
Closing since PR #3156 is merged
