### ISSUE TITLE
import-task-no-when: Warn if import_tasks is used with when condition

### ISSUE THREAD

**Issue by Yethal** [ansible/ansible-lint#2219]
Bad: 
```
- name: Import tasks
  ansible.builtin.import_tasks: tasks.yml
  when: some condition

```
Good:
```
- name: Import tasks
  ansible.builtin.include_tasks: tasks.yml
  when: some condition
```
If we have files with dozens or even hundreds of tasks and we add them to a play conditionally using `import_tasks` instead of `include_tasks` the play output will show each and every of those tasks individually (marked as skipped) which severely reduces output readability (since it's now cluttered with skipped tasks). There may also be a small performance penalty to this but I don't have a playbook large enough to test this at hand.

**Comment by ssbarnea** [comment]
While easy to implement, I am not really sure if there are no genuine ways where you want to use `import_task + when` instead. I cannot think of one yet but before we implement it we need bit more feedback from others.

I do see the benefits, no question about that.

**Comment by bcoca** [comment]
This might be a misuse of `import` in your case, but it does not mean that using conditionals on `import` is always wrong.

The conditional is evaluated PER task, so if it depends on variables or conditions that change within the list of tasks imported, the tasks skipped/run can also change.  

The check would have to KNOW that the condition is always false and only then would it make sense to give the warning. This requires being able to evaluate the import's `when` for every imported task, which only happens at runtime and can change on different runs, for example `'nginx' not in package_facts_results`  and one of the tasks installs nginx .

**Comment by ssbarnea** [comment]
My take: if we can find some kind of proof that 80% or more of usages of import+when are mistakes, we do have a strong case for adding this rule. Those that are using it by-design could make use of no-qa to disable it.

How to get some numbers?...

**Comment by cognifloyd** [comment]
Sometimes I have to use `import_tasks` instead of `include_tasks` to make it easier to use `--start-at-task` which cannot target tasks added by `include_tasks`. So, for me it really depends. Sometimes import is better for a given playbook and how it is used, and sometimes minimizing output by using include is better.

So, I'm -1 on this proposed rule. If it's included as optional only, without plans to enable it by default, then I'm indifferent to including it.

**Comment by cidrblock** [comment]
I belive we should be able to load the `when` clasue with jinja2 and introspect the resulting object to determine if it is complex, quick example:
```python
import jinja2
import pytest

conditionals = (jinja2.nodes.And, jinja2.nodes.Or)

def to_template(string):
    return f"{{{{ {string} }}}}"


@pytest.fixture
def environment():
    def changed():
        return True
    env = jinja2.Environment()
    env.tests['changed'] = changed
    return env


def test_is_complex_and(environment):
    when = "foo is changed and bar is defined"
    string = to_template(when)
    parsed = environment.parse(string)
    complex = [node for node in parsed.body[0].nodes if isinstance(node, conditionals)]
    assert complex


def test_is_not_complex(environment):
    when = "foo is changed"
    string = to_template(when)
    parsed = environment.parse(string)
    complex = [node for node in parsed.body[0].nodes if isinstance(node, conditionals)]
    assert not complex
```

**Comment by bcoca** [comment]
@cidrblock complexity is not the issue, availability is

**Comment by ssbarnea** [comment]
I will close this as wontfix because our team will not work on implementing it, mainly because there are too many corner cases where use of it will cause invalid red flags.

Still, is someone would make PR for implementing it as an opt-in rule, we will likely not refuse it.
