### ISSUE TITLE
`jinja[spacing]` suggests breaking up negative array indices

### ISSUE THREAD

**Issue by briantist** [ansible/ansible-lint#2317]
##### Summary

```
jinja: Jinja2 spacing could be improved: {{ molecule_project_parts[-1] }} -> {{ molecule_project_parts[- 1] }} (jinja[spacing])
roles/config/vars/main.yml:9 Jinja2 template rewrite recommendation: `{{ molecule_project_parts[- 1] }}`.
```

It's suggesting that I change `{{ var[-1] }}` to `{{ var[- 1] }}` with a space between the minus sign and the integer. While it may or may not work, I would not want to make this change either way.

I do think that the previous spacing check was useful and don't want to lose that, so I don't want to disable this spacing rule outright.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
> ansible --version
ansible [core 2.13.1]
  config file = None
  configured module search path = ['/home/briantist/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/briantist/.a213/lib/python3.8/site-packages/ansible
  ansible collection location = /home/briantist/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/briantist/.a213/bin/ansible
  python version = 3.8.0 (default, Feb 25 2021, 22:10:10) [GCC 8.4.0]
  jinja version = 3.1.2
  libyaml = True

> ansible-lint --version
ansible-lint 6.5.0 using ansible 2.13.1
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### OS / ENVIRONMENT

Ubuntu 18.04 (WSL2)

##### STEPS TO REPRODUCE

```yaml
value:
  - a
  - b
  - c
  - d
var: '{{ value[-2] }}'
```

##### Desired Behavior

Leave negative literals alone.

##### Actual Behavior

See other fields.

**Comment by felixfontein** [comment]
A similarly undesired change is that `jinja[spacing]` wants to change `item[:-4]` to `item[: -4]`. I'm not 100% sure whether that should have its own issue or should be part of this one, so I'm posting it here for now.

**Comment by felixfontein** [comment]
> A similarly undesired change is that `jinja[spacing]` wants to change `item[:-4]` to `item[: -4]`. I'm not 100% sure whether that should have its own issue or should be part of this one, so I'm posting it here for now.

@ssbarnea this problem is still there, so I take it you don't see this as part of this issue? Should I create a new issue for it?
