### ISSUE TITLE
Cannot run tests with VS code with default configuration

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-lint#2335]
##### Summary

To run the tests using the VS code test tree, one of 2 configuration options needs to be added to the `launch.json` file within the `.vscode` directory.

#### Option 1:

Use the `integratedTerminal` which will have sourced the virtual environment prior to running `pytest'

```
{
            "name": "Python: Debug Tests",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "purpose": ["debug-test"],
            "console": "integratedTerminal",
            "justMyCode": false
}
```

#### Option 2

Prepend the virtual environment's `bin` directory to the system PATH:

```
{
            "name": "Python: Debug Tests",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "purpose": ["debug-test"],
            "env": {"PATH": "${workspaceFolder}/venv/bin"},
            "justMyCode": false
}

```

This will allow the `ansible-config` executable to be found in the current virtual environment.

This is not an `ansible-lint` issue, but a known issue with VS Code, here for tracking and linking purposes.

Feel free to close this, or possible we might add it to the dev docs:

Related: https://github.com/microsoft/vscode-python/issues/4300

**Comment by ajinkyau** [comment]
This seems to be fixed as we're able to see the tests in test explorer
