### ISSUE TITLE
ansible-lint needs option to treat warnings as errors

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-lint#236]
We discovered that ansible-lint has no option for treating warnings as errors which is a real issue on CI environments as warnings are often ignored and lower quality code goes in.

Few examples of warnings:

* `WARNING: Couldn't open <...> - No such file or directory`
* `[WARNING]: While constructing a mapping from` ... `duplicate dict key (size).  Using last defined value only.`

**Comment by DanyC97** [comment]
for that i guess you can use `ansible-reivew` ?

**Comment by willthames** [comment]
Some of those are ansible warnings and they are just printed out - I have no control over them. 

Having said that, ansible-review is able to detect duplicate keys (as it's able to perform analysis on inventory files and many other ansible file types)

**Comment by ssbarnea** [comment]
@willthames Is something that ansible-lint does more or better than ansible-review?

**Comment by l0b0** [comment]
This seems to be an issue still.

**Comment by peterhalasz** [comment]
It was not clear from the thread but this has been already implemented. You can use the `--strict` flag. 
See: [Code](https://github.com/ansible/ansible-lint/blob/c98fa0e50703cc81bc8e89ce9d772c280de20523/src/ansiblelint/cli.py#L346) and [PR](https://github.com/ansible/ansible-lint/pull/2533)
