### ISSUE TITLE
exclude third-party roles

### ISSUE THREAD

**Issue by afeld** [ansible/ansible-lint#238]
# Issue Type

- Feature request

# Ansible and Ansible Lint details

```
$ ansible --version
ansible 2.2.1.0
  ...
  configured module search path = Default w/o overrides
$ ansible-lint --version
ansible-lint 3.4.10
```

- ansible installation method: pip
- ansible-lint installation method: pip

# Desired Behaviour

I have a number of roles installed from Ansible Galaxy (or from GitHub directly) through a [`requirements.yml`](http://docs.ansible.com/ansible/galaxy.html#installing-multiple-roles-from-a-file) file. Since these roles are not something I wrote, linting them isn't useful. I think it would make sense to exclude the roles listed in the requirements file by default, or have a flag to do so, rather than needing to list them individually with `--exclude`.

Thanks!

**Comment by willthames** [comment]
I have no way of knowing whether a role in a requirements file is third-party or in-house. I worry that changing this behaviour might break things for people relying on linting roles in requirements.yml

**Comment by dnorthup-ums** [comment]
@willthames 

> I worry that changing this behaviour might break things for people relying on linting roles in requirements.yml

As ansible-lint doesn't appear to be pulling roles down from a repo when run it seems it would make the most sense to just ignore a role if it is listed in the `requirements.yml` file. I use ansible-lint to check for errors in my current work. I really don't care if there are errors in another role that will need to be pulled from a separate repository prior to being able to run my plays, as those playbooks and roles should have been QA'd prior to being pushed up to the repository. (We are using both GitHub hosted roles and local repository hosted roles.)

**Comment by willthames** [comment]
I'd really just recommend using [ansible-review](https://github.com/willthames/ansible-review) and only reviewing the files you actually want to review. 

If there is a patch that ignores roles that are in requirements.yml, or can accept an `--exclude roles` or similar, that would be given due consideration.

**Comment by jharley** [comment]
I ended up adding `--exclude meta` to stop linting dependencies.  This seems to have done the trick, but I'm curious if there's any side effects.

I also feel that linting a dependant role is not helpful.

**Comment by ssbarnea** [comment]
Not a bug, it is possible to exclude any path if you want.

**Comment by dnorthup-ums** [comment]
@ssbarnea I'm not sure I follow your logic here. We *ALREADY* knew that we could exclude local filesystem paths. That *was not* the concern.

**Comment by Marek77** [comment]
@ssbarnea please consider reopening. We have some roles which come from a different team and so not available at lint time; currently I'm using a workaround in .ansible-lint:

```
warn_list:
  - internal-error
```

but that's ugly and I'm not sure if the internal error would not hide other issues.

**Comment by ssbarnea** [comment]
I know the code well enough to say that this will not happen. It is not technically possible to perform linting with incomplete "code".
