### ISSUE TITLE
ansible-lint ignores the # noqa jinja[spacing] tag

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible-lint#2382]
##### Summary

In the DebOps codebase, there's [a role which uses `when` parameter in a list](https://github.com/debops/debops/blob/master/ansible/roles/owncloud/defaults/main.yml#L1081-L1092). This is a separate issue [to be resolved later](https://github.com/debops/debops/issues/2187), for now the offending lines have been marked with `# noqa jinja[spacing]` tag to tell `ansible-lint` to ignore them. But it's not working, they still show up in the linting output:
```
jinja: Jinja2 spacing could be improved: {{ owncloud__release is version_compare("8.2", "<=") }} -> owncloud__release is version_compare("8.2", "<=") (jinja[spacing])
ansible/roles/owncloud/defaults/main.yml:1086

jinja: Jinja2 spacing could be improved: {{ owncloud__ldap_enabled | bool }} -> owncloud__ldap_enabled | bool (jinja[spacing])
ansible/roles/owncloud/defaults/main.yml:1089

jinja: Jinja2 spacing could be improved: {{ owncloud__smb_support | bool }} -> owncloud__smb_support | bool (jinja[spacing])
ansible/roles/owncloud/defaults/main.yml:1092
```

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
ansible --version
ansible [core 2.13.1]
  config file = None
  configured module search path = ['/home/drybjed/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/drybjed/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/drybjed/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/drybjed/.local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.1.2
  libyaml = True

ansible-lint --version
ansible-lint 6.5.2 using ansible 2.13.1

```

- ansible installation method: pip
- ansible-lint installation method: pip

##### OS / ENVIRONMENT

Debian 11 (bullseye)

##### STEPS TO REPRODUCE

The repository code is hosted publicly. With an installed `ansible-lint` you can check it using:

```console (paste below)
git clone https://github.com/debops/debops /tmp/debops
cd /tmp/debops
make lint

```

##### Desired Behavior

The lines marked as `noqa` should be ignored by `ansible-lint`

##### Actual Behavior

They're not ignored. :-)

**Comment by juanvalino** [comment]
Same problem here
