### ISSUE TITLE
Feature Request - Progress Bar while running ansible-lint

### ISSUE THREAD

**Issue by vikas027** [ansible/ansible-lint#240]
# Issue Type
- Feature request

# Desired Behaviour

It would be great to have some kind of progress bar. It is very useful to have the progress when we have a large number of files. If that's too cumbersome, may be a spinning cursor.

# Actual Behaviour 

`ansible-lint` takes some time without showing any output on the screen.

**Comment by ssbarnea** [comment]
wontfix, current version is so fast that it does not need any progress.
