### ISSUE TITLE
write_list causes failure for rule yaml[comments]

### ISSUE THREAD

**Issue by Sickafant** [ansible/ansible-lint#2458]
##### Summary

I'm using ansible-lint as a pre-commit hook in addition to yamllint. When I use the `write_list: all` feature to autofix formatting issues, it causes the linting to fail for rule `yaml: too few spaces before comment (yaml[comments])`. Ideally the auto-formatting should obey .yamllint rules, or be configurable in .ansible-lint so that I can match up the two tools.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
 ansible --version
 ansible 2.10.17
   config file = /Users/USERNAME/.ansible.cfg
   configured module search path = ['/Users/USERNAME/.ansible/plugins/         modules', '/usr/share/ansible/plugins/modules']
   ansible python module location = /Users/USERNAME/.local/pipx/venvs/ansible- base/lib/python3.10/site-packages/ansible
   executable location = /Users/USERNAME/.local/bin/ansible
   python version = 3.10.6 (main, Aug 30 2022, 04:58:14) [Clang 13.1.6 (clang- 1316.0.21.2.5)]

 ansible-lint --version
 WARNING: PATH altered to include /Users/USERNAME/.local/pipx/venvs/ansible-   lint/bin
 ansible-lint 6.5.2 using ansible 2.13.4

```

- ansible installation method: pipx on macOS
- ansible-lint installation method: pipx on macOS

##### OS / ENVIRONMENT

macOS Monterey 12.5.1 (21G83), Macbook M1 Pro

##### STEPS TO REPRODUCE

Minimal test case has 3 files in a folder:

```console (paste below)
$ tree -a
.
├── .ansible-lint
├── .yamllint
└── playbooks
    └── test.yml

1 directory, 3 files
```

file contents:
```console
$ cat .ansible-lint
---
use_default_rules: true

write_list:
  - all
$ cat .yamllint
---
extends: default
$ cat playbooks/test.yml
---
- name: Test
  hosts: all
  tasks:
    - name: Test  # comment 2-space indent
      ansible.builtin.debug:
        msg: Hello world
```

Steps to run:
```console
$ ansible-lint
```
Run it once, resulting in modified file.
Run it again, results in lint failure.

##### Desired Behavior

Ideally it follows yamllint default of preferring 2 space indent, and does not modify the file. Following that, there won't be an ansible-lint failure for `yaml[comments]`

##### Actual Behavior

```console
$ ansible-lint
WARNING: PATH altered to include /Users/USERNAME/.local/pipx/venvs/ansible-lint/bin

Modified 1 files.
Finished with 0 failure(s), 0 warning(s) on 1 files.
$ ansible-lint
WARNING: PATH altered to include /Users/USERNAME/.local/pipx/venvs/ansible-lint/bin
WARNING  Listing 1 violation(s) that are fatal
yaml: too few spaces before comment (yaml[comments])
playbooks/test.yml:5

You can skip specific rules or tags by adding them to your configuration file:
# .config/ansible-lint.yml
warn_list:  # or 'skip_list' to silence them completely
  - yaml[comments]  # Violations reported by yamllint.

Finished with 1 failure(s), 0 warning(s) on 1 files.
```

WORKAROUND:

Add a one-indent rule to .yamllint:
```console
$ cat .yamllint
---
extends: default
rules:
  comments:
    min-spaces-from-content: 1
```

This makes yamllint rule match the ansible-lint auto-formatting, . But there is no way to use 2-space comment indents if you prefer that.

**Comment by ssbarnea** [comment]
I will have to close this as wontfix because even if someone implements it, it will create a conflix with prettier, which does not have a configurable option.
