### ISSUE TITLE
Show location of deprecation warning

### ISSUE THREAD

**Issue by BonaBeavis** [ansible/ansible-lint#246]
# Issue Type
- Feature request

# Ansible and Ansible Lint details

```
ansible 2.2.1.0
ansible-lint 3.4.11
```

- ansible installation method: pip
- ansible-lint installation method: pip

# Desired Behaviour
```
[DEPRECATION WARNING]: docker is kept for backwards compatibility but usage is 
discouraged. The module documentation details page may explain more about this 
rationale..
This feature will be removed in a future release. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
```
Deprecation warnings should show their location like this:
```
/home/foo/Work/cis/roles/create-jenkins-job/tasks/main.yml:7
Task/Handler: Request crumb
```

**Comment by willthames** [comment]
The deprecation warnings come from the underlying ansible methods - ansible-lint doesn't actually do the deprecation warnings at all. 

I agree that this would be good to have, but I'm not sure how easy it would be.

**Comment by ssbarnea** [comment]
I am going to close this because this fully depends on Ansible core and afaik there are no plans for them to make these warnings collectable.
