### ISSUE TITLE
Error while parsing role `meta.yml` file: "schema: 'standalone' is a required property (schema[meta])"

### ISSUE THREAD

**Issue by nre-ableton** [ansible/ansible-lint#2463]
In ansible-lint 6.6.0, a new version of the schema now requires a `standalone` variable to be specified in roles. This property was made optional in https://github.com/ansible/schemas/pull/389 (and schemas were updated in https://github.com/ansible/ansible-lint/pull/2439/files, which appears in the 6.6.0 changelog), so I suspect something isn't quite right.

This is especially confusing, because the `standalone` property seems to have been invented independently of other Ansible development efforts in https://github.com/ansible/schemas/pull/387. It doesn't exist in the official documentation for either [`galaxy.yml` files](https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html) or role [`meta.yml` files](https://galaxy.ansible.com/docs/contributing/creating_role.html#role-metadata).

**Comment by ssbarnea** [comment]
Fixed in https://github.com/ansible/ansible-lint/releases/tag/v6.6.1

**Comment by nre-ableton** [comment]
@ssbarnea Thanks!
