### ISSUE TITLE
RFE: Discourage 2+ deep plugin directory in collections

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-lint#2584]
When we get to a point when we traverse the python content within a collection, we should discourage subdirectories in the plugins folder.

This could also be done by checking for more than 3 parts in a plugin's canonical name.

**Comment by ssbarnea** [comment]
I propose implementing this as a subrule of `fqcn`, one named `fqcn[deep]`. The tricky big about it is that it needs to run only on module calls with more than two dots that are coming from the current collection as it does not make sense for us to discourage someone to to use deep modules from collections authored by someone else.
