### ISSUE TITLE
Lock File Deadlock Issue

### ISSUE THREAD

**Issue by StephenDillon** [ansible/ansible-lint#2654]
With the latest release (ansible-lint==6.8.5), when you stop a running ansible-lint via ctrl + z it doesn't seem to remove the lock file.
Trying to run ansible-lint following this just hangs for a few minutes then exists with below error message.
'Timeout waiting for another instance of ansible-lint to release the lock.'

It does not give you the location of the lock file or any way to resolve this issue, ending in effectively a corrupt workspace.
Can we augment the error message to print the location of the lock file or associate the lock file with the process so subsequent runs can clean up the file when they detect a lock file associated to a dead process.

**Comment by ssbarnea** [comment]
Sorry but it seems that you do not know what Ctrl-Z means, see https://superuser.com/questions/476873/what-is-effect-of-ctrl-z-on-a-unix-linux-application

Ctrl-C is supposed to stop the app. If it runs in background, it will wait for the process to finish. If is suspended it will never finish unless it is resumes. That is not a bug, it is a feature.

**Comment by StephenDillon** [comment]
Thank you for quick response @ssbarnea !

Interesting, so it should eventually resolve? It occured about a hour ago with the process normally finishing within a minute, so I highly doubt there is a running waiting process blocking the lock file from being removed. 

I suspect I ctrl c it but possible could have been z, either 
way the main process would have well finished and after multiple attempts with the same user / venv ect, it definitely looks to be left in a permanently locked state

**Comment by cognifloyd** [comment]
No, Ctrl-Z pauses execution of the app so it does not progress and cannot finish. Type `fg` to bring it to the foreground and continue, or `bg` to let it finish in the background.
