### ISSUE TITLE
ansible-lint runs collection code when validating Jinja2 expressions

### ISSUE THREAD

**Issue by felixfontein** [ansible/ansible-lint#2681]
##### Summary

While working on tests for a filter plugin (https://github.com/felixfontein/ansible-acme/pull/41) I noticed that when linting the integration tests for the filter, which contain some tests that make the plugin raise an exception, ansible-lint seems to evaluate the expressions and thus run code from the collection. This effectively causes linting to fail since the Jinja2 expressions raise an error when being evaluated, as you can see in https://github.com/felixfontein/ansible-acme/actions/runs/3456077642/jobs/5768559703:

```
WARNING  Listing 4 violation(s) that are fatal
jinja[invalid]: Unexpected templating type error occurred on ({{ {} | felixfontein.acme._substitute_dns({}) }}): The DNS name is of type <class 'dict'>, and not text. The DNS name is of type <class 'dict'>, and not text
tests/integration/targets/filter__substitute_dns/tasks/main.yml:34 Task/Handler: Filter errors (1/5)

jinja[invalid]: Unexpected templating type error occurred on ({{ 'wc.example.net' | felixfontein.acme._substitute_dns([]) }}): The substitution map type <class 'list'>, and not a dictionary. The substitution map type <class 'list'>, and not a dictionary
tests/integration/targets/filter__substitute_dns/tasks/main.yml:41 Task/Handler: Filter errors (2/5)
You can skip specific rules or tags by adding them to your configuration file:

jinja[invalid]: Unexpected templating type error occurred on ({{ 'wc.example.net' | felixfontein.acme._substitute_dns({'a': 1}) }}): Key or value of dictionary entry are of type <class 'str'> resp. <class 'int'>, but both must be text. Key or value of dictionary entry are of type <class 'str'> resp. <class 'int'>, but both must be text
tests/integration/targets/filter__substitute_dns/tasks/main.yml:55 Task/Handler: Filter errors (4/5)

jinja[invalid]: Unexpected templating type error occurred on ({{ 'wc.example.net' | felixfontein.acme._substitute_dns({1: 'a'}) }}): Key or value of dictionary entry are of type <class 'int'> resp. <class 'str'>, but both must be text. Key or value of dictionary entry are of type <class 'int'> resp. <class 'str'>, but both must be text
tests/integration/targets/filter__substitute_dns/tasks/main.yml:62 Task/Handler: Filter errors (5/5)

Error: Unexpected templating type error occurred on ({{ {} | felixfontein.acme._substitute_dns({}) }}): The DNS name is of type <class 'dict'>, and not text. The DNS name is of type <class 'dict'>, and not text
Error: Unexpected templating type error occurred on ({{ 'wc.example.net' | felixfontein.acme._substitute_dns([]) }}): The substitution map type <class 'list'>, and not a dictionary. The substitution map type <class 'list'>, and not a dictionary
Error: Unexpected templating type error occurred on ({{ 'wc.example.net' | felixfontein.acme._substitute_dns({'a': 1}) }}): Key or value of dictionary entry are of type <class 'str'> resp. <class 'int'>, but both must be text. Key or value of dictionary entry are of type <class 'str'> resp. <class 'int'>, but both must be text
Error: Unexpected templating type error occurred on ({{ 'wc.example.net' | felixfontein.acme._substitute_dns({1: 'a'}) }}): Key or value of dictionary entry are of type <class 'int'> resp. <class 'str'>, but both must be text. Key or value of dictionary entry are of type <class 'int'> resp. <class 'str'>, but both must be text
```

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

Both the latest development versions and the latest released versions (installed with `pip`)

##### STEPS TO REPRODUCE

Check out the PR, remove commit https://github.com/felixfontein/ansible-acme/pull/41/commits/1301d6c60cd5a2b02a27185f544c0bd984519eba which ignores `jinja[invalid]`, and run `ansible-lint`.

##### Desired Behavior

Linting should pass (or complain about something else).

##### Actual Behavior

`jinja[invalid]` linting errors are reported

**Comment by felixfontein** [comment]
I guess now this discussion is moot since now ansible-lint intentionally executes user-supplied code (#2749). From my POV this has a huge security impact and is very problematic.

**Comment by felixfontein** [comment]
I doubt that #2821 fixes this, since this issue is about **filters**, not about **lookups**.

**Comment by ssbarnea** [comment]
@felixfontein AFAIK they are basically the same thing. I tested after removing the two jinja excludes from its config and I still did not see any failures, even reported passing production profile. There are still warnings about unable to load modules but that is due to missing a `requirements.yml` in repo root. Any reason for not having one?

**Comment by felixfontein** [comment]
If you look in ansible-core's source, you can see that the only thing that `disable_lookups=True` does is
```
            if disable_lookups:
                t.globals['query'] = t.globals['q'] = t.globals['lookup'] = self._fail_lookup
```
So it really only disables lookups, but neither filter plugins nor test plugins.

**Comment by felixfontein** [comment]
> There are still warnings about unable to load modules but that is due to missing a requirements.yml in repo root. Any reason for not having one?

Collection requirements are specified in galaxy.yml. Everything else is handled on runtime.

**Comment by felixfontein** [comment]
https://github.com/felixfontein/ansible-acme/pull/47 still fails with latest `main` branch.

**Comment by felixfontein** [comment]
https://github.com/felixfontein/ansible-acme/pull/47 still fails with the latest `main` branch, so the bug has still not been fixed.

**Comment by briantist** [comment]
I'm seeing this today, I admit I'm not on the latest version but since upgrading is so painful I'd like to not go through that if the problem is not actually fixed. @felixfontein do you know if anything changed since May?

**Comment by ssbarnea** [comment]
I raised https://github.com/ansible/ansible-lint/issues/3831 as while jinja2 was fixed, I do think we now have a problem with ArgsRule https://github.com/ansible/ansible-lint/issues/3831

There are only two rules that instantiate code, jinja and args ones. Let me know if I got this right.

**Comment by felixfontein** [comment]
Jinja2 has not been fixed. (And #3831 also mentions another big code execution problem.)
