### ISSUE TITLE
tilde (~) characters in $PATH are not expanded to $HOME

### ISSUE THREAD

**Issue by maxamillion** [ansible/ansible-lint#2688]
##### Summary

`~` characters in `$PATH` are not expanded to `$HOME`

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

- ansible installation method: source
- ansible-lint installation method: pip

##### STEPS TO REPRODUCE

When attempting to add ansible-lint to the Azure Pipelines of the [osbuild.composer Collection](https://github.com/ansible-collections/osbuild.composer), I found that the `PATH` environment variable in the CI container had `~` characters in it instead of absolute paths.

https://dev.azure.com/ansible/osbuild.composer/_build/results?buildId=60423&view=logs&j=2671e6a6-f41a-533c-2720-8ffdcf8ab96f&t=5b604a49-baaa-558f-6ab2-4a2ff646af4f&l=354

```console (paste below)
PATH -> '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:~/.local/bin'
00:19 + command -v ansible
00:19 /home/AzDevOps_azpcontainer/.local/bin/ansible
00:19 + pip install ansible-lint==6.8.4 --disable-pip-version-check
00:20 Collecting ansible-lint==6.8.4
00:20   Downloading ansible_lint-6.8.4-py3-none-any.whl (232 kB)
00:20 Collecting rich>=9.5.1
00:20   Downloading rich-12.6.0-py3-none-any.whl (237 kB)
00:20 Requirement already satisfied: pyyaml in /usr/local/lib/python3.9/dist-packages (from ansible-lint==6.8.4) (6.0)
00:21 Collecting ruamel.yaml<0.18,>=0.15.34
00:21   Downloading ruamel.yaml-0.17.21-py3-none-any.whl (109 kB)
00:21 Requirement already satisfied: ansible-core>=2.12.0 in /home/AzDevOps_azpcontainer/.local/lib/python3.9/site-packages (from ansible-lint==6.8.4) (2.15.0.dev0)
00:21 Collecting black>=22.1.0
00:21   Downloading black-22.10.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.5 MB)
00:21 Collecting ansible-compat>=2.2.1
00:21   Downloading ansible_compat-2.2.4-py3-none-any.whl (19 kB)
00:21 Collecting yamllint>=1.25.0
00:21   Downloading yamllint-1.28.0-py2.py3-none-any.whl (62 kB)
00:21 Requirement already satisfied: packaging in /usr/local/lib/python3.9/dist-packages (from ansible-lint==6.8.4) (21.3)
00:21 Collecting filelock
00:24   NOTE: The current PATH contains path(s) starting with `~`, which may not be expanded by all applications.
00:24 Successfully installed ansible-compat-2.2.4 ansible-lint-6.8.4 attrs-22.1.0 black-22.10.0 bracex-2.3.post1 click-8.1.3 commonmark-0.9.1 filelock-3.8.0 jsonschema-4.17.0 mypy-extensions-0.4.3 pathspec-0.10.2 platformdirs-2.5.4 pygments-2.13.0 pyrsistent-0.19.2 rich-12.6.0 ruamel.yaml-0.17.21 ruamel.yaml.clib-0.2.7 subprocess-tee-0.3.5 tomli-2.0.1 typing-extensions-4.4.0 wcmatch-8.4.1 yamllint-1.28.0
00:24 + ansible-lint --profile=production
00:24 Failed to find ansible executable in PATH
```

##### Desired Behavior

ansible-lint to run

Possible security bugs should be reported via email to `security@ansible.com`

**Comment by ssbarnea** [comment]
I think that you missed an essential message from pip https://github.com/pypa/pip/blob/6d131137cf7aa8c1c64f1fadca4770879e9f407f/src/pip/_internal/operations/install/wheel.py#L192-L193

Ability to expand `~` in PATH has nothing to do with linter itself. You should never use `~` in PATH. Instead use $HOME at the place where you alter PATH.

**Comment by darthwalsh** [comment]
> You should never use `~` in PATH. Instead use $HOME at the place where you alter PATH.

I didn't understand why this would be the case at first, until I ran into the problem myself.

Your shell expands `~` in PATH lookup, but `/usr/bin/env` and `/usr/bin/which` don't. Some more context: 
 https://stackoverflow.com/a/44704799/771768
