### ISSUE TITLE
Poetry vs. will-not-work-on-windows-try-from-wsl-instead since >= 6.9.0 on Linux

### ISSUE THREAD

**Issue by encbladexp** [ansible/ansible-lint#2816]
##### Summary

We are using Poetry to manage our dependencies. Until 6.8.X we never had issues with it, but since 6.9.0 poetry isn't able to
update ansible-lint anymore.

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

Arch Linux, Current Updates, Python 3.10.

```console (paste below)
~ poetry --version
Poetry (version 1.3.1)
~ ansible --version
ansible [core 2.13.7]
  ...
  python version = 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]
  jinja version = 3.1.2
  libyaml = True
~ ansible-lint --version
ansible-lint 6.9.1 using ansible 2.13.7
```

- ansible installation method: Poetry
- ansible-lint installation method: Poetry

##### STEPS TO REPRODUCE

```console (paste below)
~ cat pyproject.toml 
[tool.poetry]
name = "github-test"
version = "0.0.1"
description = "Test"
authors = [ "Test <test@user.com>" ]

[tool.poetry.dependencies]
python = "^3.8"
ansible-lint = "~6.9.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"



~ poetry update
Updating dependencies
Resolving dependencies... (2.7s)

Because no versions of ansible-lint match >6.9.0,<6.9.1 || >6.9.1,<6.10.0
 and ansible-lint (6.9.0) depends on will-not-work-on-windows-try-from-wsl-instead (*), ansible-lint (>=6.9.0,<6.9.1 || >6.9.1,<6.10.0) requires will-not-work-on-windows-try-from-wsl-instead (*).
And because ansible-lint (6.9.1) depends on will-not-work-on-windows-try-from-wsl-instead (*), ansible-lint (>=6.9.0,<6.10.0) requires will-not-work-on-windows-try-from-wsl-instead (*).
So, because no versions of will-not-work-on-windows-try-from-wsl-instead match *
 and github-test depends on ansible-lint (~6.9.0), version solving failed.
```

##### Desired Behavior

ansible-lint could be, as most other software, be installed with Poetry.

##### Actual Behavior

ansible-lint could not be installed in a current release with Poetry on a Linux System with "only" Python 3.10 too:
```
pip install will-not-work-on-windows-try-from-wsl-instead
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.11,<4.0
ERROR: Could not find a version that satisfies the requirement will-not-work-on-windows-try-from-wsl-instead (from versions: none)
ERROR: No matching distribution found for will-not-work-on-windows-try-from-wsl-instead
```

I assume the issue is related to the package constraints.

(Not that important, but: Where is the source code of this will-not-work-on-windows-try-from-wsl-instead thing?)

**Comment by arrrgi** [comment]
Have the same issue since #2712 was merged.

@encbladexp the `will-not-work-on-windows-try-from-wsl-instead` dependency is a phony/non-existent dependency which **pip install** handles gracefully, while Poetry just expects the package to exist and bails out as there is no such package on Pypi.org, etc

**Comment by encbladexp** [comment]
Exactly, an improvement would be to avoid such module, but use `platform.system` in ansible-lint to stop working when Windows as Platform is detected. It would also avoid another dependency which could introduce issues at any time.

**Comment by ssbarnea** [comment]
Duplicate #2795
