### ISSUE TITLE
`data/profiles.yml` missing from package

### ISSUE THREAD

**Issue by freswa** [ansible/ansible-lint#2826]
# Issue Type

- Bug report

# Ansible and Ansible Lint details

```
ansible --version 2.14.1
ansible-lint --version (broken) 6.10.0
```

- ansible installation method: OS package
- ansible-lint installation method: OS package

# Desired Behavior

`ansible-lint --version` doesn't crash

# Actual Behavior (Bug report only)

`ansible-lint --version` crashes due to `data/profiles.yml` being missing.

It seems since tha latest PEP-621 changes, the profiles.yml file isn't packaged anymore?

**Comment by freswa** [comment]
```
schemas/__store__.json
schemas/ansible-lint-config.json
```
Are missing as well

**Comment by ssbarnea** [comment]
I am sorry to dissapoint you but if you run `tox -e pkg` you will see that all binary files are includes in both archives from dist/ (src dist and wheel), so that is not a bug. Probably you did not use official tool-chain to install the project.

**Comment by freswa** [comment]
@ssbarnea Do you have documentation available how distributions are supposed to build this project? Do you intend be built with PEP 517 python-build or do you hard require tox?

**Comment by ssbarnea** [comment]
This has nothing to do with tox. Just run `python -m build` to trigger a build. If the outcome from this does not include the required files, we might have a real packaging bug inside the repo. That bit is implementing PEP-517

**Comment by freswa** [comment]
I found the culprit. I forgot to include the setuptools-scm dependency. Weird, that it fails silently by ignoring all the json and yaml files, but I should've read the pyproject.toml. Thanks @ssbarnea

**Comment by ssbarnea** [comment]
That is weird, especially as we have https://github.com/ansible/ansible-lint/blob/main/pyproject.toml#L1-L7 -- it might make sense to investigate the issue a little bit as I can see this happening again. Ideally people should not be able to reach a situation like the one you faced.
