### ISSUE TITLE
Dependency Cache Directory

### ISSUE THREAD

**Issue by uberjew666** [ansible/ansible-lint#2845]
#### Summary

The documentation claims all collections and roles are cached in {project_dir}/.cache but it seems to default to /home/{USER}/.cache. For the life of me, I cannot seem to change this to {project_dir}/.cache. I've tried several parameters in ansible.cfg but none seem to have an effect.

How does one go about changing the cache directory?

##### Issue Type

- Bug report

# Ansible and Ansible Lint details

```
ansible --version
7.1.0
ansible-lint --version
6.9.1
```

- ansible installation method: pip
- ansible-lint installation method: pip

# Desired Behavior

To change the cache directory for collections to {project_dir}/.cache

# Actual Behavior (Bug report only)

Defaults to /home/{USER}/.cache always

**Comment by 2mc** [comment]
I have the same problem and want to have `.cache` under `{project_dir}`.

How did you finally go about changing the cache directory?

**Comment by uberjew666** [comment]
I set this environment variable:
XDG_CACHE_HOME=".cache/"

You may need to set this too (change the 6e90fc to whatever your requires)
ANSIBLE_COLLECTIONS_PATHS=".cache/ansible-compat/6e90fc/collections"

**Comment by 2mc** [comment]
Thank you!

Prefixing the `ansible-lint` command with `XDG_CACHE_HOME=".cache"` does indeed the job.

P.S. You then still get this `.cache/ansible-compat/...` path rubbish which is not quite what the `ansible-lint` documentation says — but never mind.
