### ISSUE TITLE
Collection dependencies from galaxy.yml not skipped in offline mode

### ISSUE THREAD

**Issue by jensrudolf** [ansible/ansible-lint#2922]
# Issue Type

- Bug report

# Ansible and Ansible Lint details

```
ansible [core 2.13.3]
ansible-lint 6.11.0 using ansible 2.13.3
```

- ansible installation method:  pip
- ansible-lint installation method: pip

# Desired Behavior

Offline mode should not try to download/install collection dependencies specified in galaxy.yml as it breaks CI pipelines. It should assume that dependencies have been installed in ANSIBLE_COLLECTIONS_PATH locations and skip the call to ansible-galaxy.

# Actual Behavior (Bug report only)

1. Create new collection e.g. with ``ansible-galaxy collection init test.test``
2. Edit galaxy.yml and add a dependency (e.g. ``test.dep: '*'``)
3. Run ansible-lint in offline mode within collection dir ```ansble-lint --offline```

Ansible-lint calles ansible-galaxy and tries to download the collection.

```
WARNING  Retrying execution failure 1 of: ansible-galaxy collection install -vvv --force -p /home/401840/.cache/ansible-compat/9f86d0/collections .
ERROR    Command returned 1 code:
ansible-galaxy [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/401840/.cache/ansible-compat/9f86d0/modules', '/home/401840/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/401840/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/401840/.cache/ansible-compat/9f86d0/collections:/home/401840/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/401840/.local/bin/ansible-galaxy
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.0.1
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
Starting galaxy collection install process
Process install dependency map
Opened /home/401840/.ansible/galaxy_token

ERROR! Failed to resolve the requested dependencies map. Could not satisfy the following requirements:
* test.dev:* (dependency of test.test:1.0.0)
```

As the collection does not exist on galaxy.ansible.com, this will break. This will also break any CI pipeline running in a restricted / disconnected environment without access to public galaxy hub.

**Comment by jensrudolf** [comment]
Note that is does not help installing the dependency locally and pointing the ANSIBLE_COLLECTIONS_PATHS variable to it as ansible-galaxy is invoked with ```-p <path-to-temp-dir>```.

**Comment by dsavineau** [comment]
I hit this too as I need some collections not available on galaxy.ansible.com and preinstalled prior the ansible-lint execution.

**Comment by bluikko** [comment]
Is it due to this change that after updating from 6.11.x to 6.12.2 now everything outside of `ansible.builtin` are again not found in offline mode?
A ton of `Unable to load module` warnings and failures using filters from collections?

```
WARNING  Skipped installing collection dependencies due to running in offline mode.
WARNING  Unable to load module community.docker.docker_swarm at roles/swarm/tasks/main.yml:3 for options validation
WARNING  Unable to resolve FQCN for module community.docker.docker_swarm
...
jinja[invalid]: An unhandled exception occurred while templating '...'. Error was a <class '
ansible.errors.AnsibleError'>, original message: lookup plugin (ansible.utils.index_of) not found
...
                   Rule Violation Summary
 count tag            profile rule associated tags
     2 jinja[invalid] basic   formatting
```
