### ISSUE TITLE
meta-runtime (meta-unsupported-ansible): Refactor and adding SpecifierSet check

### ISSUE THREAD

**Issue by alisonlhart** [ansible/ansible-lint#2999]
Rename `meta-unsupported-ansible rule` to `meta-runtime` for a more accurate name. 

Add SpecifierSet (valid version with operators) check for the `requires_ansible` key value. This will verify that the version value is a valid version under Pythonic requirements.

Note: This is the final piece to satisfy the `runtime.yml` file checks that exist in galaxy-importer. 

Extends #2102

**Comment by alisonlhart** [comment]
This is almost complete. We are doing final documentation edits.

**Comment by ajinkyau** [comment]
@alisonlhart @ssbarnea closing this out as the related PR is merged
