### ISSUE TITLE
How to handle / distinguish openSUSE Leap and e.g. openSUSE Leap Micro (or openSUSE MicroOS or ...)

### ISSUE THREAD

**Issue by johanneskastl** [ansible/ansible-lint#3077]
https://github.com/ansible/ansible-lint/blob/b2bb9f635c2adb844895e921e8cc4ac1072addfe/src/ansiblelint/schemas/meta.json#L1126

openSUSE has several different distributions, where some of them are using transactional updates. This means a read-only rootfs where package installation requires a reboot.

In "normal" ansible this is handled by different values for `ansible_os_family`:
- `Suse` is normal SUSE or openSUSE Leap or openSUSE Tumbleweed
- `openSUSE MicroOS` is the transactional one based on Tumbleweed
- `openSUSE Leap Micro` is the transactional one based on Leap
-  there should be one for SLE Micro, but I have not yet used that

How to properly put them into the meta/main.yml of e.g. a role or collection?

1. Put them in as `opensuse` and add a comment that this is (only or also or not) working on e.g. Leap  Micro?
2. Put them in as separate platforms, even though they are not defined in the `schemas/meta.json` above?

I guess the same questions appears in Fedora vs. Fedora CoreOS or RHEL vs. RHEL CoreOS.

**Comment by ssbarnea** [comment]
Just document it and add an `fail` in your code if you **know** that detected version is not supported by you. Be gentle about unknown values as you might not want to prevent people from using your code just because they have a newer versions that you did not test.

Fail is good only for known broken cases, for others only a warning.

**Comment by johanneskastl** [comment]
> Just document it and add an `fail` in your code if you **know** that detected version is not supported by you. Be gentle about unknown values as you might not want to prevent people from using your code just because they have a newer versions that you did not test.
> 
> Fail is good only for known broken cases, for others only a warning.

Sorin, I think you partially misunderstood me. I can of course make the code do the needful and handle those system. 

I was mainly talking about the schema that Ansible-lint uses for the platforms. I was wondering if I should state those variants explictly (which would trigger an error), if I should add a comment while only specifying `opensuse` or `Suse`, ...
