### ISSUE TITLE
Add EDA rulebook into JSON schemas

### ISSUE THREAD

**Issue by alisonlhart** [ansible/ansible-lint#3079]
Event-Driven Ansible is introducing a new type of Ansible content: rulebooks. The content of the rulebooks is YAML. The EDA team has already created a JSON schema for rulebooks. 

Add this JSON schema into ansible-lint schema checks:
https://github.com/ansible/ansible-rulebook/blob/main/ansible_rulebook/schema/ruleset_schema.json

The schema is getting updates, but the minimum requirements should not change from this point forward.

**Comment by ssbarnea** [comment]
Can you please profile a file-path glob pattern for identifying rulebooks? We need that in order to know when to apply that schema.

**Comment by alisonlhart** [comment]
(Per slack conversation)

`rulebooks/*.y[a]ml`
EDA rulebooks reference: https://github.com/ansible/event-driven-ansible/tree/main/rulebooks
