### ISSUE TITLE
Ansible Lint reports the `decrypt` parameter in the `ansible.builtin.copy` module is not supported

### ISSUE THREAD

**Issue by alessfg** [ansible/ansible-lint#3110]
##### Summary

Ansible Lint reports the `decrypt` parameter in the `ansible.builtin.copy` module is not supported.

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console
$ ansible --version
ansible [core 2.14.3]
  config file = /Users/a.faelgarcia/.ansible.cfg
  configured module search path = ['/Users/a.faelgarcia/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/a.faelgarcia/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.2 (main, Feb 16 2023, 02:55:59) [Clang 14.0.0 (clang-1400.0.29.202)] (/opt/homebrew/opt/python@3.11/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True

$ ansible-lint --version
ansible-lint 6.13.1 using ansible 2.14.3

$ python --version
Python 3.11.2
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### STEPS TO REPRODUCE

1. Create a task/playbook containing the `ansible.builtin.copy` module and using the `decrypt` parameter:

```yaml
- name: (Alpine Linux) Copy NGINX Plus certificate
  ansible.builtin.copy:
    src: "{{ nginx_license['certificate'] }}"
    dest: /etc/apk/cert.pem
    decrypt: true
    mode: "0444"
```

2. Run Ansible Lint

```console
$ ansible-lint
...
args[module]: Unsupported parameters for ansible.builtin.copy module: decrypt. Supported parameters include: _original_basename, attributes, backup, checksum, content, dest, directory_mode, follow, force, group, local_follow, mode, owner, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate (attr). (warning)
tasks/plus/setup-license.yml:15 Task/Handler: (Alpine Linux) Copy NGINX Plus certificate
...
```

##### Desired Behavior

Per the `ansible.builtin.copy` module docs, the `decrypt` parameter should be supported https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html#parameter-decrypt

```console
$ ansible-lint

Passed with production profile: 0 failure(s), 0 warning(s) on 1 files.
```

##### Actual Behavior

```console
$ ansible-lint
...
args[module]: Unsupported parameters for ansible.builtin.copy module: decrypt. Supported parameters include: _original_basename, attributes, backup, checksum, content, dest, directory_mode, follow, force, group, local_follow, mode, owner, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate (attr). (warning)
tasks/plus/setup-license.yml:15 Task/Handler: (Alpine Linux) Copy NGINX Plus certificate
...
```

**Comment by ajinkyau** [comment]
@alessfg I can confirm this bug, however I can also see that you're passing `decrypt: true` which per the docs is the default value for decrypt, so you don't need to pass this explicitly.
Reference: https://docs.ansible.com/ansible/2.8/user_guide/vault.html#file-level-encryption

@ssbarnea Did I miss something?

**Comment by ssbarnea** [comment]
Nope, time to add another internal exception to the rule.

**Comment by MarkusTeufelberger** [comment]
copy is an action plugin and a module, probably `decrypt` is only part of the action plugin interface and ansible-lint only looks at the module part.

**Comment by alessfg** [comment]
It is the default value indeed but for various reasons we ended up deciding to explicitly include it. Thanks for the quick turnaround!
