### ISSUE TITLE
jinja[invalid] violation using variable reference in `json_query` filter

### ISSUE THREAD

**Issue by PierreBart** [ansible/ansible-lint#3140]
##### Summary

This issue is similar to https://github.com/ansible/ansible-lint/issues/3047.

When referencing a variable in a `json_query` filter, `ansible-lint` in  `v6.14.0` incorrectly lists a `jinja[invalid]` rule violation and log the following exception:
 ```shell
An unhandled exception occurred while templating '...TEMPLATE...'. Error was a <class 'ansible.errors.AnsibleFilterError'>, original message: Error in jmespath.search in json_query filter plugin:
'...VARIABLE...' is undefined
```

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
ansible-lint --version
ansible-lint 6.14.0 using ansible 2.14.3
```

- ansible installation method: poetry, MacOS ARM
- ansible-lint installation method: poetry, MacOS ARM

##### STEPS TO REPRODUCE

I use the same example as in https://github.com/ansible/ansible-lint/issues/3047, the only difference being the `json_query` filter inside a `vars:` section of a task. 

1. Copy the below playbook and save it as `playbook.yaml`:
```yaml
---

- name: "Grafana playbook"
  hosts: "localhost"
  tasks:
    - name: "Register previously copied dashboards"
      ansible.builtin.find:
        paths: "/etc/grafana/dashboards"
        hidden: true
        patterns:
          - "*.json"
      register: "dashboards_present"

    - name: "Get dashboard lists"
      set_fact:
        test_var: "{{ _dashboards_present_list }}"
      vars:
        _dashboards_present_list: "{{ dashboards_present | json_query('files[*].path') | default([]) }}"
```
2. Run `ansible-lint playbook.yaml`

##### Desired Behavior

`ansible-lint` does not report a rule violation error.

##### Actual Behavior

`ansible-lint` outputs:
```shell
$ ansible-lint playbook.yaml
WARNING  Listing 1 violation(s) that are fatal
playbook.yaml:16: jinja[invalid]: An unhandled exception occurred while templating '{{ dashboards_present | json_query('files[*].path') | default([]) }}'. Error was a <class 'ansible.errors.AnsibleFilterError'>, original message: Error in jmespath.search in json_query filter plugin:
'dashboards_present' is undefined
Read documentation for instructions on how to ignore specific rule violations.

              Rule Violation Summary
 count tag            profile rule associated tags
     1 jinja[invalid] basic   formatting

Failed after min profile: 1 failure(s), 0 warning(s) on 1 files.
```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve

**Comment by ssbarnea** [comment]
I am unable to reproduce this bug with code from main branch and I know that once of the merged fixes was related to jinja rule.

**Comment by PierreBart** [comment]
I tested with https://github.com/ansible/ansible-lint/commit/e571d54fa064b5d7bdc337b3de7fe689ea96c5a0 and can confirm I no longer see the issue 👍.

I will wait for the release.
