### ISSUE TITLE
Changelog lacking

### ISSUE THREAD

**Issue by aairey** [ansible/ansible-lint#333]
# Issue Type
- Feature request

# Ansible and Ansible Lint details

```bash
ansible --version
ansible 2.3.3.0
  config file = /home/aairey/git_projects/trimbletl/ansible-playbook-infra/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

ansible-lint --version
ansible-lint 3.4.19
```

- ansible installation method: pip
- ansible-lint installation method: pre-commit

# Desired Behaviour

I updated my pre-commit hooks and I saw ansible-lint got updated.
```bash
pre-commit autoupdate
Updating git://github.com/pre-commit/pre-commit-hooks...[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
updating v1.2.0 -> v1.2.3.
Updating https://github.com/willthames/ansible-lint.git...[INFO] Initializing environment for https://github.com/willthames/ansible-lint.git.
updating v3.4.20 -> v3.5.0rc1.
```

I came here to github to check what has changed in between versions, but on the releases tab it was not visible.
Then I went searching for a `CHANGELOG.md` which also seems not to be present.

Could we have some way to track what has changed in between versions?

**Comment by willthames** [comment]
I've added a CHANGELOG.md for 3.4.22 (I've decided not to update to 3.5.0 now as there aren't any breaking changes)

**Comment by martey** [comment]
I noticed that the CHANGELOG file hasn't been merged to master. Is this on purpose?

@willthames, would a pull request containing a more comprehensive changelog be useful?

**Comment by willthames** [comment]
Now merged to master (an oversight)

A more comprehensive changelog would indeed be useful - I'll leave this open if you wish to raise a PR referencing it.

**Comment by awcrosby** [comment]
Closing as CHANGELOG and ROADMAP currently being maintained.
