### ISSUE TITLE
Test running on PPC arch getting dependency failures

### ISSUE THREAD

**Issue by ashwinik30** [ansible/ansible-lint#3336]
##### Summary
Tryng to run sanity/unit/integration testing on power for https://github.com/ansible/ansible-lint repo

Tried to clone https://github.com/ansible/ansible-lint repo on power (ppc64le arch)
build package with python3 -m build
trying to run tests on ansible-link source path 
##### Issue Type

- Bug Report

##### OS / ENVIRONMENT
ppc64lr rhel8

```console (paste below)
ansible-lint --version
testing main branch
platform linux -- Python 3.9.13, pytest-7.3.1, pluggy-1.0.0
rootdir: /root/ansible-lint
configfile: pyproject.toml

```

- ansible installation method: one of source, pip, OS package
- ansible-lint installation method: one of source, pip, OS package

pip

##### STEPS TO REPRODUCE

git clone https://github.com/ansible/ansible-lint
   yum install java-17-openjdk-devel openssl-devel git wget tar python39-devel gcc rust cargo -y
python3 -m build
pip3 install .
pytest

```console (paste below)
Eroor we are getting
FATAL: For testing, we require pyyaml to be installed with its native extension, missing it would make testing 3x slower and risk missing essential bugs.


```
[root@ibm-p9z-18-lp4 ansible-lint]# pytest
FATAL: For testing, we require pyyaml to be installed with its native extension, missing it would make testing 3x slower and risk missing essential bugs.
[root@ibm-p9z-18-lp4 ansible-lint]#

```

<!--- HINT: You can paste gist.github.com links for larger files -->

##### Desired Behavior

<!--- Describe what you expected to happen when running the steps above -->

Possible security bugs should be reported via email to `security@ansible.com`

##### Actual Behavior

<!--- Describe what happened. If possible run with extra verbosity (-vvvv) -->

Please give some details of what is happening.
Include a [minimum complete verifiable example] with:

- minimized playbook to reproduce the error
- the output of running ansible-lint including the command line used
- if you're getting a stack trace, also the output of
  `ansible-playbook --syntax-check playbook`

<!--- Paste verbatim command output between triple backticks -->

```paste below

```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve

**Comment by ssbarnea** [comment]
First, you should create an upstream feature request to compile pyyaml for PPC architecture and link it to this ticket.

As I doubt that the upstream bug will be fixed in no time, you can make a pull-request to make our special test for binary-pyyaml be skipped for ppc architecture.

**Comment by ashwinik30** [comment]
> compile pyyaml for PPC architecture

hi @ssbarnea  Created issue https://github.com/yaml/pyyaml/issues/710
