### ISSUE TITLE
Too broad pattern for Ansible Var Files results in spurious errors working with pandoc defaults file

### ISSUE THREAD

**Issue by chrisgrieser** [ansible/ansible-lint#3341]
I suspect that the problem is not with `ansiblelint` but rather with the schemastore (where I created an issue: https://github.com/SchemaStore/schemastore/issues/2919 ), but in case the problem is indeed created by `ansiblelint` rather than the schemastore, I am also opening an issue here.

---

The problem: Apparently, schemas defined in this repo get pulled by the [schemastore](https://github.com/SchemaStore/schemastore). The [yaml-lsp](https://github.com/redhat-developer/yaml-language-server), in turn, by default pulls yaml schemas from the schemastore and applies them to the yaml files I am working with.

Now this would be totally fine, if it wasn't that some schemas seem to have a pattern that is so broad that it also matches yaml files that aren't ansible files and results in tons of spurious errors there. In particular, I am working with pandoc defaults file, which must be stored in a directory called `defaults`, which [matches the pattern defined in the ansible vars file schema](https://github.com/ansible/ansible-lint/blob/main/src/ansiblelint/schemas/vars.json). This results in the LSP treating completely unrelated pandoc defaults files as ansible files, leading to tons of spurious errors, which I, as a user cannot even really disable on my end.

It took me quite a bit of trail-following to figure out that an LSP error was actually created by a file in this repo. Since the broad pattern `defaults/*.yml` probably makes sense for this linter, I assume that the root problem is caused by the schemastore. But in case someone from this repo is responsible for pushing the schemas to the schema store, I am also reporting this here.

**Comment by ssbarnea** [comment]
@chrisgrieser That conflict may prove tricky to address as involves 4-5 repositories from multiple projects. AFAIK, the `examples` block from within the schema is used only our test suite, as nobody else is reading it.

First, I want to see a repository example where the pandoc yaml is incorrectly identified, as I need to see the full path of the file. Once we establish these, we might know how to narrow down the matching patterns and update:

- the examples in schema (this repo)
- the patterns in schemastore project
- possible YAML extension and Ansible extension too

I will try to help you, but I first need to example as I need to play a little bit with the pattern changes in order to update them.

**Comment by ssbarnea** [comment]
That seems like an unfortunate decision on pandoc side, basically they will never be able to get good support for their yaml because it is not unique enough.

**Comment by chrisgrieser** [comment]
well, to be honest, I think the issue lies somewhere along the trail of schemastore and yaml-ls, since somewhere there they apply a schema for ansible files to *all* yaml files in "defaults" directory? 

I mean, basically any application that stores yaml files in such a directory will get spurious LSP errors.

**Comment by chrisgrieser** [comment]
> changing the configuration of your editor to force it to use a difference JSON Schema for these documents. 

only problem with that solution is that there is no schema for pandoc default files available (I checked in the schema store), and yaml-ls in turn is only able to *change* the schema of a document manually, but not able to *disable* schemas for a file 🙈 
https://github.com/redhat-developer/yaml-language-server/issues/446

> You should also contact pandoc folks and ask them to consider switching to a different file-naming pattern (less generic) to avoid conflicts like this.

yeah, I'll try that, but to be honest, I again don't blame them to choose a generic file-naming pattern, but rather the fact that somewhere between yaml-ls and the schemastore the schema gets applied too broadly.

**Comment by jgm** [comment]
> basically they will never be able to get good support for their yaml because it is not unique enough.

Pandoc maintainer here. We're not particularly concerned with getting highlighting support for the YAML.  But it's quite annoying that a generic name like defaults/*.yml gets automatically linted as ansible, leading users to get spurious recommendations.  Ansible is squatting on a generic name.  Something beyond that name should be required to trigger specific linting suggestions.

**Comment by jgm** [comment]
We can't really change either due to backwards compatibility.  However, if on your end you're able to exclude cases of the form
`.pandoc/defaults/*.{yml,yaml}`
`pandoc/defaults/*.{yml,yaml}`
that would take care of it, I think.
