### ISSUE TITLE
Fedora 38 is missing

### ISSUE THREAD

**Issue by Commandcracker** [ansible/ansible-lint#3352]
##### Summary

Fedora 38 is missing from [schemas/meta.json](https://github.com/ansible/ansible-lint/blob/bb025ae8983746ef9dfd6b9485e40331f1efaace/src/ansiblelint/schemas/meta.json)
and it is already present in [galaxy.ansible.com/api/v1/platforms](https://galaxy.ansible.com/api/v1/platforms/)!

**Comment by ajinkyau** [comment]
closing since related PR: #3353 is merged
