### ISSUE TITLE
Ansible lint 6.11.0 broken since release of ansible-compat 4.X

### ISSUE THREAD

**Issue by SRv6d** [ansible/ansible-lint#3393]
##### Summary

Just like with https://github.com/ansible-community/molecule/issues/3903, ansible-lint broke with the latest major release of ansible-compat.

##### Issue Type

- Bug Report

```
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
  File "/usr/local/lib/python3.10/site-packages/ansiblelint/__main__.py", line 344, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
  File "/usr/local/lib/python3.10/site-packages/ansiblelint/__main__.py", line 197, in main
    initialize_options(argv[1:])
  File "/usr/local/lib/python3.10/site-packages/ansiblelint/__main__.py", line 110, in initialize_options
    options.cache_dir = get_cache_dir(options.project_dir)
  File "/usr/local/lib/python3.10/site-packages/ansible_compat/prerun.py", line 13, in get_cache_dir
    basename = project_dir.resolve().name.encode(encoding="utf-8")
AttributeError: 'str' object has no attribute 'resolve'
```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve

**Comment by ssbarnea** [comment]
Please install a newer version, we have no current plans to keep maintenance branches. AFAIK, latest few releases are not impacted by the publication of the newer major version of ansible-compat. Obviously that you also have option to pin down the ansible-compat version to prevent the new version from being installed.

**Comment by dvzrv** [comment]
FWIW, this is also broken with ansible-lint 6.15.0 on Arch Linux now (cc @jelly @freswa).
I have just built and tested it:

```
Traceback (most recent call last):
  File "/usr/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
  File "/usr/lib/python3.10/site-packages/ansiblelint/__main__.py", line 354, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
  File "/usr/lib/python3.10/site-packages/ansiblelint/__main__.py", line 194, in main
    initialize_options(argv[1:])
  File "/usr/lib/python3.10/site-packages/ansiblelint/__main__.py", line 112, in initialize_options
    options.cache_dir = get_cache_dir(options.project_dir)
  File "/usr/lib/python3.10/site-packages/ansible_compat/prerun.py", line 13, in get_cache_dir
    basename = project_dir.resolve().name.encode(encoding="utf-8")
AttributeError: 'str' object has no attribute 'resolve'
```

@ssbarnea you have introduced a lot of breaking changes in [ansible-compat 4.0.1](https://github.com/ansible/ansible-compat/releases/tag/v4.0.1) (4.0.0 got silently deleted?!) and molecule is also affected by these changes (see https://github.com/ansible-community/molecule/issues/3903) - which I was already able to fix for the downstream package.
I am still a bit clueless how to fix this particular problem for ansible-lint though. Maybe you have an idea about where to look?

> Obviously that you also have option to pin down the ansible-compat version to prevent the new version from being installed.

Defining supported version upper boundaries would be something that ansible-lint and also molecule should define in their projects (not the user of those projects who might not even be Python developers).

**Comment by dvzrv** [comment]
@ssbarnea anything before this commit is broken with ansible-compat 4.0.1:

https://github.com/ansible/ansible-lint/commit/2fca3fed958702a2b40dd454511ea1b9f624c740

**Comment by dvzrv** [comment]
No, I am packaging `ansible-compat` for Arch Linux (we're already far past ansible-lint 6.11.0 - please *read* what I wrote above... the described issue affects *all versions* up until https://github.com/ansible/ansible-lint/commit/2fca3fed958702a2b40dd454511ea1b9f624c740 as there is no locking to ensure specific ansible-compat versions).

In system packaging (e.g. for Arch Linux) we can also not lock, which is why l will bump ansible-lint to the aforementioned commit to have a working set of packages again, unless you're about to do a patch level release for ansible-lint anyways (probably warranted given that things are kind of broken across the board now).

When updating central dependencies such as `ansible-compat` great care should to be taken not to break its consumers (after all, you seem to maintain all of them).

**Comment by SRv6d** [comment]
@ssbarnea I fully emphasize with not supporting older versions of ansible lint, but if ansible-lint breaks for users even though they pinned their version due to a downstream library that is also maintained by ansible, this is clearly a bug. It cannot be the users responsibility to pin ansible lints (over 100!) dependencies manually. Worse yet, there is no simple upgrade path to the latest version, because breaking changes (new default linting rules) were introduced in the meantime.
