### ISSUE TITLE
Example rules that run against roleName/meta/main.yml fail to work as expected.

### ISSUE THREAD

**Issue by jrtaisto** [ansible/ansible-lint#342]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible --version
2.5.2
ansible-lint --version
3.4.21
 python -V
Python 3.5.1  (using virtual env on CentOS 7.4.1708)
```
- ansible installation method: pip
- ansible-lint installation method: pip

# Desired Behaviour

When using ansible-galaxy init and modifying the meta/main.yml file, expect the dependencies: [] line to not be flagged by the EEXTRA0012 rule.  Also don't expect the EEXTRA0013 rule to be flagged unless missing one of the following galaxy_info items:  author, description, company, min_ansible_version, platforms, license.  Note this is a fresh ansible-lint pip install and I simply copied the example rules to a custom location.  The config is meant to use as many rules provided as possible.

# Actual Behaviour (Bug report only)

Please give some details of what is actually happening.
Include a [minimum complete verifiable example](http://stackoverflow.com/help/mcve)
with:
- role created with ansible-galaxy init.
- output of running ansible-lint:  Running against a role directory.
$ ansible-lint -c ansible-lint.conf roles/TeamGPGkey/
Examining /home/myID/ansible_env/roles/TeamGPGkey/tasks/main.yml of type tasks
Examining /home/myID/ansible_env/roles/TeamGPGkey/handlers/main.yml of type handlers
Examining /home/myID/ansible_env/roles/TeamGPGkey/meta/main.yml of type meta
/home/myID/ansible_env/roles/TeamGPGkey/tasks/main.yml:5: [EEXTRA0012] meta/main.yml should not declare dependencies
/home/myID/ansible_env/roles/TeamGPGkey/tasks/main.yml:5: [EEXTRA0013] meta/main.yml should contain: author, description, company, min_ansible_version, platforms, license

$ cat ansible-lint.conf
parseable: true
quiet: true
rulesdir:
  - ~/ansible_env/custom_linter_rules
skip_list:
  - skip_this_tag
  - and_this_one_too
use_default_rules: true
verbosity: 1

$ cat /home/myID/ansible_env/roles/TeamGPGkey/tasks/main.yml
galaxy_info:
  author: First Last
  description: Team GPG key for custom RPMs.
  company: Some company
  license: BSD
  min_ansible_version: 2.5
  platforms:
  - name: CentOS
    versions:
    - 7
    - 6
  - name: EL
    versions:
    - 7
    - 6
  - name: AIX
    versions:
    - 7.1
    - 7.2
  galaxy_tags:
  - ONE_TWO_THREE
  - TEST
  - QA
  - DEV
dependencies: []

$ ansible-lint -c ansible-lint.conf -L
ANSIBLE0002: Trailing whitespace
  There should not be any trailing whitespace
ANSIBLE0004: Git checkouts must contain explicit version
  All version control checkouts must point to an explicit commit or tag, not just "latest"
ANSIBLE0005: Mercurial checkouts must contain explicit revision
  All version control checkouts must point to an explicit commit or tag, not just "latest"
ANSIBLE0006: Using command rather than module
  Executing a command when there is an Ansible module is generally a bad idea
ANSIBLE0007: Using command rather than an argument to e.g. file
  Executing a command when there is are arguments to modules is generally a bad idea
ANSIBLE0008: Deprecated sudo
  Instead of sudo/sudo_user, use become/become_user.
ANSIBLE0009: Octal file permissions must contain leading zero
  Numeric file permissions without leading zero can behave in unexpected ways. See http://docs.ansible.com/ansible/file_module.html
ANSIBLE0010: Package installs should not use latest
  Package installs should use state=present with or without a version
ANSIBLE0011: All tasks should be named
  All tasks should have a distinct name for readability and for --start-at-task to work
ANSIBLE0012: Commands should not change things if nothing needs doing
  Commands should either read information (and thus set changed_when) or not do something if it has already been done (using creates/removes) or only do it if another check has a particular result (when)
ANSIBLE0013: Use shell only when shell functionality is required
  Shell should only be used when piping, redirecting or chaining commands (and Ansible would be preferred for some of those!)
ANSIBLE0014: Environment variables don't work as part of command
  Environment variables should be passed to shell or command through environment argument
ANSIBLE0015: Using bare variables is deprecated
  Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ("{{your_variable}}").
ANSIBLE0016: Tasks that run when changed should likely be handlers
  If a task has a `when: result.changed` setting, it's effectively acting as a handler
ANSIBLE0017: become_user requires become to work as expected
  become_user without become will not actually change user
ANSIBLE0018: Deprecated always_run
  Instead of always_run, use check_mode.
EXTRA0001: Variables should have spaces after {{ and before }}
  Variables should be of the form {{ varname }}
EXTRA0002: The lineinfile module is typically nasty
  While lineinfile supports some idemptotency, using template or assemble modules to populate configuration files is preferred
EXTRA0004: Use connection: local rather than delegate_to: localhost
  Connection: local ensures that unexpected delegated_vars don't get set (e.g. {{ inventory_hostname }} used by vars_files)
EXTRA0005: Most files should not contain tabs
  Tabs can cause unexpected display issues. Use spaces
EXTRA0006: Lines should be no longer than 100 chars
  Long lines make code harder to read and code review more difficult
EXTRA0007: use connection: local rather than host: localhost
  Using hosts: localhost limits the quality of variables available to your playbook
EXTRA0008: plays should not contain logic
  plays should not contain tasks, handlers or vars
EXTRA0009: hosts files should not contain group vars
  Use inventory group_vars directory rather than [group:vars] in hosts file
EXTRA0010: hosts files should not contain host vars
  Use inventory host_vars directory rather than host key=value in hosts file
EXTRA0012: meta/main.yml should not declare dependencies
  Dependencies hurt the ability to maintain versioned roles
EXTRA0013: meta/main.yml should contain relevant info
  meta/main.yml should contain: author, description, company, min_ansible_version, platforms, license
EXTRA0014: Don't compare to literal True/False
  Use `when: var` rather than `when: var == True` (or conversely `when: not var`)
EXTRA0015: Don't compare to empty string
  Use `when: var` rather than `when: var != ""` (or conversely `when: not var` rather than `when: var == ""`)

**Comment by willthames** [comment]
Please use triple backticks to preserve formatting, particularly of YAML files.

**Comment by awcrosby** [comment]
Checking this with the current source seems to work as expected. There is no flag about dependencies, and the flag about missing platforms is expected.
```
$ ansible-galaxy init test-init-role
$ ansible-lint -p test-init-role/
test-init-role/meta/main.yml:1: [E701] Role info should contain platforms        
test-init-role/meta/main.yml:1: [E703] Should change default metadata: author    
test-init-role/meta/main.yml:1: [E703] Should change default metadata: description
test-init-role/meta/main.yml:1: [E703] Should change default metadata: company   
test-init-role/meta/main.yml:1: [E703] Should change default metadata: license
```
