### ISSUE TITLE
Installing requirements from galaxy.yml fails for git dependencies

### ISSUE THREAD

**Issue by gone-for-coding** [ansible/ansible-lint#3485]
##### Summary

Installing dependencies via galaxy.yml (as newly introduced) fails for git dependencies.

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
# ansible-lint --version
ansible-lint 6.16.2 using ansible-core:2.15.0 ruamel-yaml:0.17.26 ruamel-yaml-clib:0.2.7
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### STEPS TO REPRODUCE

Put the `galaxy.yml` example below in a directory and try to lint.

```yaml
namespace: "namespace_name"
name: "collection_name"
version: "1.0.0"
readme: "README.md"
authors:
  - "Author1"
dependencies:
  "git+https://mygit.com/repository.git": "main"
```

##### Desired Behavior

Installation should work just fine as it does with `requirements.yml`.

##### Actual Behavior

```console (paste below)
root@012e7485c4a0:/code# ansible-lint -v
INFO     Identified / as project root due file system root.
INFO     Provisioning collection git+https://mygit.com/repository.git:main from galaxy.yml
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ansiblelint/__main__.py", line 310, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ansiblelint/__main__.py", line 258, in main
    app = get_app()
          ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ansiblelint/app.py", line 387, in get_app
    app.runtime.prepare_environment(
  File "/usr/local/lib/python3.11/site-packages/ansiblelint/_vendor/ansible_compat/runtime.py", line 511, in prepare_environment
    self.install_collection(
  File "/usr/local/lib/python3.11/site-packages/ansiblelint/_vendor/ansible_compat/runtime.py", line 344, in install_collection
    if matches and CollectionVersion(matches[1]).is_prerelease:
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ansiblelint/_vendor/ansible_compat/runtime.py", line 73, in __init__
    super().__init__(version)
  File "/usr/local/lib/python3.11/site-packages/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '//mygit.com/repository.git:main'
```

The issue seems to originate here: https://github.com/ansible/ansible-compat/blob/34c1459e319e22238faffa9ff86a214ee26905f8/src/ansible_compat/runtime.py#L48

**Comment by ssbarnea** [comment]
Hi! Based on official documentation from https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html I am inclined to believe that that is not supported.

**Comment by gone-for-coding** [comment]
I wonder if this is just missing in the documentation, as it is actually working just fine.

Also I found various places in the documentation, where git is supported:
- https://docs.ansible.com/ansible/latest/collections_guide/collections_installing.html#installing-a-collection-from-a-git-repository
- https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-multiple-roles-from-a-file
- https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#using-meta-main-yml

Maybe we can use the same approach as with `requirements.yml` and just pass it on to `ansible-galaxy`.

**Comment by ssbarnea** [comment]
@sivel @bcoca Is the lack of documentation on purpose or we only want to support simple dependency selectors like the one documented?

I am not keen to implement support for git due to inherent problems, and also performance side effects, basically making close to impossible to make it idempotent.

I see two possible directions:
- document git as supported
- remove support for git

Note: that is about galaxy.yml files, not requirments.yml

**Comment by sivel** [comment]
galaxy.yml does not support git deps.  Installation from git is not meant to be used for any production application, and is a developer shortcut only. Anything in a galaxy.yml should be published artifacts available from a galaxy server.

**Comment by gone-for-coding** [comment]
Thanks for your comments @ssbarnea and @sivel. We will remove the git reference in `galaxy.yml` and use `requirements.yml` in the projects as an alternative.

Just out of curiosity:
As it is supported in `requirements.yml` and one can use `<collection dir>/roles/<rolename>/meta/requirements.yml` this would be a kind of an _ugly_ workaround. Or am I on a totally wrong path here?
https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#using-meta-requirements-yml
