### ISSUE TITLE
[RFE] Implement transform (--write) functionality for applicable rules

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible-lint#3634]
##### Summary

Implement write functionality for the rules in the below list as applicable.

 Must have:
- [x] [command-instead-of-shell](https://ansible.readthedocs.io/projects/lint/rules/command-instead-of-shell/#correct-code) https://github.com/ansible/ansible-lint/pull/3675
- [x] [deprecated-local-action](https://ansible.readthedocs.io/projects/lint/rules/deprecated-local-action/#correct-code) https://github.com/ansible/ansible-lint/pull/3689
- [x] [jinja[spacing]](https://ansible.readthedocs.io/projects/lint/rules/jinja/) https://github.com/ansible/ansible-lint/pull/3691
- [x] [key-order](https://ansible.readthedocs.io/projects/lint/rules/key-order/) https://github.com/ansible/ansible-lint/pull/3705
- [x] [no-free-form](https://ansible.readthedocs.io/projects/lint/rules/no-free-form/) https://github.com/ansible/ansible-lint/pull/3725
- [x] [no-jinja-when](https://ansible.readthedocs.io/projects/lint/rules/no-jinja-when/) https://github.com/ansible/ansible-lint/pull/3721
- [x] [no-log-password](https://ansible.readthedocs.io/projects/lint/rules/no-log-password) https://github.com/ansible/ansible-lint/pull/3708
- [x] [partial-become](https://ansible.readthedocs.io/projects/lint/rules/partial-become/) https://github.com/ansible/ansible-lint/pull/3692

Good to have:

- [ ] [deprecated-module](https://ansible.readthedocs.io/projects/lint/rules/deprecated-module/)
- [ ] [empty-string-compare ](https://ansible.readthedocs.io/projects/lint/rules/empty-string-compare/)
- [x] [fqcn](https://ansible.readthedocs.io/projects/lint/rules/fqcn/)
- [ ] [inline-env-var/](https://ansible.readthedocs.io/projects/lint/rules/inline-env-var/)
- [ ] [literal-compare](https://ansible.readthedocs.io/projects/lint/rules/literal-compare/)
- [ ] [no-tabs](https://ansible.readthedocs.io/projects/lint/rules/no-tabs)
- [ ] [risky-file-permissions](https://ansible.readthedocs.io/projects/lint/rules/risky-file-permissions/)
- [ ] [risky-octal](https://ansible.readthedocs.io/projects/lint/rules/risky-octal/)

Won't do:

- [ ] [package-latest](https://ansible.readthedocs.io/projects/lint/rules/package-latest/)
- [ ] [var-naming[non-string]](https://ansible.readthedocs.io/projects/lint/rules/var-naming/)
- [ ] [var-naming[non-ascii]](https://ansible.readthedocs.io/projects/lint/rules/var-naming/)
- [ ] [var-naming[non-jinja]](https://ansible.readthedocs.io/projects/lint/rules/var-naming/)
- [ ] [var-naming[pattern]](https://ansible.readthedocs.io/projects/lint/rules/var-naming/)
- [ ] [var-naming[no-role-prefix]](https://ansible.readthedocs.io/projects/lint/rules/var-naming/)
- [ ] [var-naming[no-reserved]](https://ansible.readthedocs.io/projects/lint/rules/var-naming/)
- [ ] [deprecated-bare-vars](https://ansible.readthedocs.io/projects/lint/rules/deprecated-bare-vars/) https://github.com/ansible/ansible-lint/pull/3688
- [ ] [no-handler](https://ansible.readthedocs.io/projects/lint/rules/no-handler/) https://github.com/ansible/ansible-lint/pull/3732

```console (paste below)
ansible-lint --version
6.17.2
```

**Comment by bendem** [comment]
Maybe it would be best to stabilise the `--write` behaviour before implementing more of it? Currently, `--write` with no rules enabled will reformat every single file parsed based on the non-configurable rueaml parsers. Since the first lint rule is yamllint which has different default and is actually configurable, running ansible-lint with `--write` produces useless changes, breaks the rules defined in further linting and often times results in broken yaml.

See #3603, #3583, #3226, #2941, #2112.

**Comment by cognifloyd** [comment]
I have implementations for a variety of rules, but I held off putting them in until I could the the Jinja formatter. Sadly, work priorities have kept me away from this project for awhile but I hope to return to it. I just don't have a precise timeline.

**Comment by ganeshrn** [comment]
@bendem Thanks for linking the related issues. We are looking into fixing those issues.

@cognifloyd A big thank you for contributing the transform feature.  Can you please do a draft PR for rules that you have implemented the transform functionality? We can look into other rules for implement the transform functionality.

**Comment by cidrblock** [comment]
https://github.com/ansible/ansible-lint/issues/3624

This is releated, we might want to take care of this prior to too many additions.

**Comment by justjais** [comment]
@cognifloyd Thanks so much for your effort in implementing the transform features from Ansible Lint. As we're currently focusing on implementing transform capabilities for one's that's mentioned in the issue description, it'd be great if you can comment ASAP with the transform capabilities that you've already worked on, as that'd help us in not duplicating the work and the effort.

**Comment by shatakshiiii** [comment]
Some related bugs: https://github.com/ansible/ansible-lint/issues/3670, https://github.com/ansible/ansible-lint/issues/3662

**Comment by ssbarnea** [comment]
I am going to close this as done as all the MUST have were implemented. This does not mean that we will not want to do the others, but we should consider this epic done for now.

Many of the ones that were not implemented were for good reasons: there is no safe way to do it programetely, a human needing to tune the result.
