### ISSUE TITLE
Update profile summary to show (only) correct message

### ISSUE THREAD

**Issue by sgabenov** [ansible/ansible-lint#3660]
##### Summary

After specifying a profile in `.ansible-lint` i am not able to see lint results for this profile.

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
ansible-lint --version
ansible-lint 6.17.2 using ansible-core:2.15.2 ansible-compat:4.1.5 ruamel-yaml:0.17.32 ruamel-yaml-clib:0.2.7
```

##### STEPS TO REPRODUCE

```console (paste below)
cat .ansible-lint
---
# .ansible-lint
profile: min # min, basic, moderate, safety, shared, production
<omitting output>


ansible-lint
WARNING  Skipped installing collection dependencies due to running in offline mode.
WARNING  Skipped installing collection dependencies due to running in offline mode.

Passed: 0 failure(s), 0 warning(s) on 774 files. Profile 'min' was required, but only 'production' profile passed.
```

##### Desired Behavior

I expect to see results for `min` profile even if i have another profile, that pass the results.
The only possibility to see results is to set `profile: null`, but it will show all errors. This is not what i expect to have.

##### Actual Behavior

Ansible-lint check all available profiles, and show message, that you have another profile that pass the check. For originally requested profile - check omits result output

```paste below
ansible-lint
WARNING  Skipped installing collection dependencies due to running in offline mode.
WARNING  Skipped installing collection dependencies due to running in offline mode.

Passed: 0 failure(s), 0 warning(s) on 774 files. Profile 'min' was required, but only 'production' profile passed.
```

**Comment by ssbarnea** [comment]
Current version display a message like:
```
Profile 'min' was required, but 'production' profile passed.
```

I will close the bug. Still, if you know a better way to phrase the result, we can adjust it even more.
