### ISSUE TITLE
Lint all yaml in tasks/ and handlers/ regardless of import or include

### ISSUE THREAD

**Issue by awcrosby** [ansible/ansible-lint#373]
# Issue Type
- Feature request

# Ansible and Ansible Lint details

```
(vgal) awc:code$ ansible --version
ansible 2.6.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/awc/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/awc/code/vgal/lib/python2.7/site-packages/ansible
  executable location = /home/awc/code/vgal/bin/ansible
  python version = 2.7.15 (default, Sep 21 2018, 23:26:48) [GCC 8.1.1 20180712 (Red Hat 8.1.1-5)]
(vgal) awc:code$ ansible-lint --version
ansible-lint 3.4.23
```

- ansible installation method: pip
- ansible-lint installation method: pip

# Desired Behaviour
Currently when linting a role, ansible-lint looks at tasks in `tasks/main.yml` and `handlers/main.yml`, and follows task files imported or included. 

Proposal: to lint all yaml files inside `tasks/` and `handlers/` regardless of whether they have been imported or included from `main.yml`

With an include in `main.yml`, `databases.yml` is linted:
```
(vgal) awc:code$ ls role_test1/tasks/
databases.yml  main.yml
(vgal) awc:code$ cat role_test1/tasks/main.yml 
---
- name: using git module
  action: git repo=blah

- include: databases.yml
(vgal) awc:code$ ansible-lint -p -r galaxy-lint-rules/rules/ role_test1
/home/awc/code/role_test1/tasks/databases.yml:2: [E105GAL] Deprecated with_X for loops
/home/awc/code/role_test1/tasks/main.yml:4: [E401] Git checkouts must contain explicit version
```

Currently without the include in `main.yml`, `databases.yml` is not linted:
```
(vgal) awc:code$ cat role_test1/tasks/main.yml 
---
- name: using git module
  action: git repo=blah
(vgal) awc:code$ ansible-lint -p -r galaxy-lint-rules/rules/ role_test1
/home/awc/code/role_test1/tasks/main.yml:4: [E401] Git checkouts must contain explicit version

```

**Comment by lwm** [comment]
> Proposal: to lint all yaml files inside tasks/ and handlers/ regardless of whether they have been imported or included from main.yml

Sounds good to me :+1:

**Comment by willthames** [comment]
This seems mostly reasonable to me - I worry that it might break stuff relying on this not happening - could we make this configurable (even if it's on by default)

**Comment by chrisjohnson** [comment]
It seems like in ansible 2.4.3 this behavior was present but something has changed since then. I agree that this is how things should operate, even if it has to be configured that way.

**Comment by lwm** [comment]
Thanks a lot @AlekseiSidorenko, I've taken a quick look. Hope this gets merged soon.

**Comment by awcrosby** [comment]
@AlekseiSidorenko thanks for the contribution! 2 items I noticed: 

I think you have to give `.endswith()` a tuple as this resolves to False: `'main.yml'.endswith('.yaml' or '.yml')`

When there _is_ an include for other files like `- include: databases.yml` that file gets linted twice. One approach might be to filter out duplicates by adding this line `files = {x['path']: x for x in files}.values()` above this:

https://github.com/ansible/ansible-lint/blob/991079d5a865c5fb4a6dd05242b5058cb57bff41/lib/ansiblelint/__init__.py#L237-L239

**Comment by AlekseiSidorenko** [comment]
Thanks for the tips, got it!

I've done with the both points, please check it.
If you don't mind, in the second case I used the following construction to simplify code understanding:
`        # remove duplicates from files list
        files = [value for n,value in enumerate(files) if value not in files[:n]] `

**Comment by tgadiev** [comment]
Are there any news? Any corrections needed?

**Comment by awcrosby** [comment]
#462 was merged
