### ISSUE TITLE
Error running ansible-lint in vscode -- RuntimeError("Could not determine home directory.")

### ISSUE THREAD

**Issue by cosmikwolf** [ansible/ansible-lint#3741]
##### Summary

I have successfully used ansible-lint in the past, but all of a sudden I am getting a very frustrating error that I have spent the past two hours trying to resolve, to no avail. 

When I save a .yml ansible playbook file I am working on, I get the following error as a notification in vscode:
```shell
Command failed: ansible-lint --offline --nocolor -f codeclimate "/Users/tenkai/Development/AnsibleConfigurations/sync_server/main.yml" Traceback (most recent call last): File "/opt/homebrew/Caskroom/mambaforge/base/envs/ansible/bin/ansible-lint", line 10, in <module> sys.exit(main()) ^^^^^^ File "/opt/homebrew/Caskroom/mambaforge/base/envs/ansible/lib/python3.11/site-packages/ansiblelint/__main__.py", line 209, in main path_inject() File "/opt/homebrew/Caskroom/mambaforge/base/envs/ansible/lib/python3.11/site-packages/ansiblelint/__main__.py", line 342, in path_inject paths[idx] = str(Path(path).expanduser()) ^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/homebrew/Caskroom/mambaforge/base/envs/ansible/lib/python3.11/pathlib.py", line 1385, in expanduser raise RuntimeError("Could not determine home directory.") RuntimeError: Could not determine home directory.
```

as you can see below, I am able to run ansible-lint in the terminal window, which should be using the same interpreter as the ansible-lint extension. 

##### OS / ENVIRONMENT
This is running on mac os x 14.0, using ansible extension v2.7.98 on vscode 1.182.2
I have configured the ansible python interpreter path, as well as the default vscode interpreter path to be the ansible conda executable. I have also tried specifying the specific ansible-lint path and the specific ansible path in the vscode extension

ansible-lint --version works OK when using it directly in the terminal using the same ansible-lint executable
```shell
~/Development/AnsibleConfigurations via 🅒 ansible 
zsh ❯ which ansible-lint
/opt/homebrew/Caskroom/mambaforge/base/envs/ansible/bin/ansible-lint
(ansible) 
~/Development/AnsibleConfigurations via 🅒 ansible 
zsh ❯ ansible-lint --version
ansible-lint 6.19.0 using ansible-core:2.15.4 ansible-compat:4.1.10 ruamel-yaml:0.17.32 ruamel-yaml-clib:0.2.7
(ansible) 
```

Ansible was installed using a conda environment with the following conda env file:
```conda
name: ansible
dependencies:
  - python=3.11
  - pip
  - ansible
  - ansible-lint
```

##### STEPS TO REPRODUCE

- save a file, it happens on any file identified as a ansible file 

```ansible
---
- name: Create couchdb conf directory
  hosts: all
  become: true
  ansible.builtin.file:
    path: /couchdb/conf
    state: directory
    mode: "0775"
```

```shell
Path for lint:  /opt/homebrew/Caskroom/mambaforge/base/envs/ansible/bin/ansible-lint
Validating using ansible-lint
[Info  - 4:06:10 PM] [ansible-lint] Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/ansible/bin/ansible-lint", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/ansible/lib/python3.11/site-packages/ansiblelint/__main__.py", line 209, in main
    path_inject()
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/ansible/lib/python3.11/site-packages/ansiblelint/__main__.py", line 342, in path_inject
    paths[idx] = str(Path(path).expanduser())
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/mambaforge/base/envs/ansible/lib/python3.11/pathlib.py", line 1385, in expanduser
    raise RuntimeError("Could not determine home directory.")
RuntimeError: Could not determine home directory.
```

**Comment by ssbarnea** [comment]
@cosmikwolf This exception comes from python core and I am not aware of any valid reason why this would appear under normal circumstances.

Please find a way to reproduce the issue without the linter. I am quite curious what is the value of `path` string that produces this exception.

I wonder if you have a messed system configuration like one where maybe `HOME` is not defined or is pointing to an invalid location.

I am more than happy to provide a fix for this but given what we know so far, I doubt this is a bug inside the linter.

I am also using MacOS and I was not able to make it create this exception with valid data. Still:
```
>>> Path("~~").expanduser()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ssbarnea/.pyenv/versions/3.11.4/lib/python3.11/pathlib.py", line 1385, in expanduser
    raise RuntimeError("Could not determine home directory.")
RuntimeError: Could not determine home directory.
```

Interesting, but not really a bug so far.
