### ISSUE TITLE
Allow linter to run in a pure offline mode

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-lint#3816]
We need a CLI option that would run linter in a pure offline mode:

- [ ] never run ansible-galaxy
- [ ] ignore all errors caused by missing modules, filters, plugins and roles

**Comment by ssbarnea** [comment]
@ajinkyau This can be done in multiple steps, a first one would be allow linter to fully disable the calls to ansible-galaxy install, as this affects the lightspeed bot implementation.

**Comment by ganeshrn** [comment]
In pure offline mode don't throm warnings/error if a collection/plugin/ task file is part of the dependency and not installed in the project. 
Example warnings and repo https://github.com/anshulbehl/network.bgp/pull/1

**Comment by SirUli** [comment]
In offline mode it should also not check for the [latest version](https://github.com/ansible/ansible-lint/blob/634c639293a4f50d12d6ac33cfec96efb05f4b16/src/ansiblelint/config.py#L278).
