### ISSUE TITLE
105GAL Deprecated with_X for loops - not in Ansible 2.7?

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible-lint#387]
> Note: This was copied over from the [galaxy-lint-rules] repository; please feel free to close if it doesn't currently apply to the existing or planned set of ansible-lint rules. Original issue: https://github.com/ansible/galaxy-lint-rules/issues/12

I'm wondering if the following lint rule:

```
[105GAL] Deprecated with_X for loops
```

Is meant to be live yet? I know `with_` was slated for deprecation in 2.7 (see https://github.com/ansible/ansible/pull/43795), but that PR was closed with the following message prior to 2.7.0's release:

> Closing for now.
> 
> We are not planning to continue with deprecation of with_ yet.

This is probably 90% of all the warnings I'm seeing in my own playbooks and roles when testing with this set of rules; and since `with_` is _not_ deprecated yet in Ansible, it would be best if we don't say as much using the Galaxy lint rules (at least IMHO).

**Comment by geerlingguy** [comment]
Possibly related to: https://github.com/willthames/ansible-lint/pull/384

**Comment by awcrosby** [comment]
For #384 [WithLoopRule 105](https://github.com/willthames/ansible-lint/pull/384/files#diff-5952c4aeb22749bbb554f2563d9a15cd) ... I think this was originally flagged as a future deprecation warning, but since we are holding off that deprecation, I agree we can hold off adding this rule as well.
