### ISSUE TITLE
6.21.x Module 'load-failure'

### ISSUE THREAD

**Issue by ansibleguy** [ansible/ansible-lint#3876]
##### Summary

Since Ansible-Lint 6.21.x a 'load-failure' is thrown when running it on a Collection.

Error: `load-failure: Failed to load or parse file. plugins/modules/XXX.py:27`

6.20.3 did not behave that way.

It seems the line that is referenced by the error message is the one where the `run_module` function is placed.

I could not find any collection-related information in the test-documentation: https://ansible.readthedocs.io/projects/lint/rules/load-failure/

The release notes also don't mention any changes related to this test: https://github.com/ansible/ansible-lint/releases

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
ansible-lint --version
> ansible-lint 6.21.1 using ansible-core:2.15.3 ansible-compat:4.1.10 ruamel-yaml:0.17.26 ruamel-yaml-clib:0.2.7
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### STEPS TO REPRODUCE

1. Have a collection to lint - like https://github.com/ansibleguy/collection_opnsense

2. Lint it

```console (paste below)
COL_DIR='~/opnsense'
TMP_COL_DIR='/tmp/ansible_lint/collections'
mkdir -p "$TMP_COL_DIR/ansible_collections/ansibleguy"
ln -s "$COL_DIR" "$TMP_COL_DIR/ansible_collections/ansibleguy/opnsense"

ANSIBLE_COLLECTIONS_PATH="$TMP_COL_DIR" ansible-lint -c .ansible-lint.yml

rm -rf "$TMP_COL_DIR"
```

##### Desired Behavior

Either provide information on how to handle this test-failure or fix its behavior.

##### Actual Behavior

The test-run fails with `load-failure: Failed to load or parse file` errors:

```
WARNING  Listing 81 violation(s) that are fatal
load-failure: Failed to load or parse file.
plugins/modules/alias.py:26

load-failure: Failed to load or parse file.
plugins/modules/alias_multi.py:27

...
```

**Comment by ssbarnea** [comment]
That seem to be caused by imports from ansible_collections, something that I think should be fine. Still, they fail and thus our linter also fails to find them.

I wonder if we should not instead have a very different approach regarding linting examples. Maybe looking at output from ansible-doc would provide more reliable? `ansible-doc --json shell`

Still, the tricky bit is to identify which plugins are inside the linted codebase. Do we have a safe way to translated a plugin path to its plugin name the way ansible-doc is expecting it?

**Comment by cidrblock** [comment]
I didn't recreate here, but it is unusual to see a URL for the examples and documentation. It is typically included in the module itself and valid yaml.

**Comment by felixfontein** [comment]
This is cauesd by `EXAMPLES` not being valid YAML. (I encountered the same problem in #5037, and tried to circumvent it with `# fmt: xxx`, which ansible-lint apparently does not know about.)
