### ISSUE TITLE
ansible-lint --fix seems to always run yaml even when yaml is not in the 'write_list'

### ISSUE THREAD

**Issue by jeffmcutter** [ansible/ansible-lint#3888]
##### Summary

ansible-lint seems to always perform autofix against yaml rules even when yaml is not included in the --fix=<>.

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
[jcutter@jcutter-fedora ~]$ cat /etc/redhat-release 
Fedora release 38 (Thirty Eight)
[jcutter@jcutter-fedora autofix]$ ansible-lint --version
ansible-lint 6.22.0 using ansible-core:2.14.11 ansible-compat:4.1.10 ruamel-yaml:0.18.5 ruamel-yaml-clib:0.2.8
```

- ansible installation method: OS package
- ansible-lint installation method: pip

##### STEPS TO REPRODUCE

```console (paste below)
---
- name: lint testing
  hosts: all
  tasks:
  - name: run command
    command: /bin/true
    register: result
    changed_when: false

# This is a comment.
  - name: debug result
    ansible.builtin.debug:
      var: result

  - name: Create file
    copy:
      content: "123"
      dest: /tmp/foo
      mode: 0644

```

##### Desired Behavior

autofix should only write changes for those included in the 'write_list' as described at:

https://ansible.readthedocs.io/projects/lint/autofix/

##### Actual Behavior

yaml rules are being updated when not included in the write_list, for example:

ansible-lint --offline --fix=none lint.yml
ansible-lint --offline --fix=fqcn,name lint.yml

Full run results:

https://gist.github.com/jeffmcutter/03b33bcc87802a991f6fa6939f3992ed

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve

**Comment by jakob1379** [comment]
It works as intented, if you read the documentation 

```man
  --fix [WRITE_LIST]    Allow ansible-lint to perform auto-fixes, including YAML reformatting. You can limit the effective rule transforms (the 'write_list') by passing a keywords 'all' or 'none' or a comma separated list of rule ids or rule tags. YAML reformatting happens whenever '--fix' or '--fix=' is used. '--fix' and '--fix=all' are equivalent: they allow all transforms to run. Presence of --fix in command overrides config file value.
```

The key-phrase being `Presence of --fix in command overrides config file value`....

My workflow for now is to use the

```man
ANSIBLE_LINT_WRITE_TMP: Tells linter to dump fixes into different temp files instead of overriding original. Used internally for testing.
```

and merge the relevant parts, which is only slightly faster than going through the output manually :/

**Comment by yump** [comment]
It works as intended, but perhaps the intention is wrong? It reformats comments, unwraps lines, unquotes a bunch of strings, and otherwise makes the diff very difficult to review. Maybe the parser knows that every character in those URLs is safe, [but I don't](https://stackoverflow.com/a/67536258).

**Comment by jakob1379** [comment]
> It works as intended, but perhaps the intention is wrong? It reformats comments, unwraps lines, unquotes a bunch of strings, and otherwise makes the diff very difficult to review. Maybe the parser knows that every character in those URLs is safe, [but I don't](https://stackoverflow.com/a/67536258).

This is by no means safe, I have had it f. Up ssh keys which was then deployed and locked me out 😅

**Comment by hrv-cta** [comment]
> My workflow for now is to use the
> 
> ANSIBLE_LINT_WRITE_TMP: Tells linter to dump fixes into different temp files instead of overriding the original. Used internally for testing.
> and merge the relevant parts, which is only slightly faster than going through the output manually :/

Hello,

Can you please provide an example of how to use this environment?
I have tried pointing at a file or a folder with no luck.

Thanks.

**Comment by jakob1379** [comment]
> > My workflow for now is to use the
> > ANSIBLE_LINT_WRITE_TMP: Tells linter to dump fixes into different temp files instead of overriding the original. Used internally for testing.
> > and merge the relevant parts, which is only slightly faster than going through the output manually :/
> 
> Hello,
> 
> Can you please provide an example of how to use this environment? I have tried pointing at a file or a folder with no luck.
> 
> Thanks.

how did you try? it works by just setting the env variable.

**Comment by hrv-cta** [comment]
> how did you try? it works by just setting the env variable.

by setting up the environment like this:
export ANSIBLE_LINT_WRITE_TMP=/docker_appdata/ansible/

then I run ansible-lint --fix --offline myfile.yml

am I missing something?

**Comment by jakob1379** [comment]
are you sure you have write permissions for `/docker_appdata/ansible/`

**Comment by hrv-cta** [comment]
> are you sure you have write permissions for `/docker_appdata/ansible/`

yes

**Comment by jakob1379** [comment]
my bad, it's a boolean flag

```bash
export ANSIBLE_LINT_WRITE_TMP=1
❯ ansible-lint --fix all.yml
....
❯ ll
.rw-r--r--  65 jga  6 Aug 09:04 -N  all.tmp.yml
.rw-r--r--  61 jga  6 Aug 09:04 -M  all.yml
```
