### ISSUE TITLE
commit 7fa5f76e0333a97476b5204487f183efb5e3d467 breaks backward compatibility of the ansible-lint github action

### ISSUE THREAD

**Issue by zerwes** [ansible/ansible-lint#3928]
##### Summary

while 2 days ago calling `ansible/ansible-lint@v6.22.0` (see https://github.com/zerwes/ansible-role-checkmkagent/actions/runs/7083656545) worked without any problems, after the commit 7fa5f76e0333a97476b5204487f183efb5e3d467 calling a tagget version of the action will fail due to the file renaming with a error (see https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense/actions/runs/7097243220/job/19317040697)

error:
```
Run wget --output-document=.git/ansible-lint-requirements.txt https://raw.githubusercontent.com/ansible/ansible-lint/main/.config/requirements-lock.txt
--2023-12-05 06:56:03--  https://raw.githubusercontent.com/ansible/ansible-lint/main/.config/requirements-lock.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 1[8](https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense/actions/runs/7097243220/job/19317040697#step:3:10)5.1[9](https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense/actions/runs/7097243220/job/19317040697#step:3:11)9.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-12-05 06:56:03 ERROR 404: Not Found.
```

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

github action

##### STEPS TO REPRODUCE

create a github action with
```yaml
jobs:
  build:
    name: ansible lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run ansible-lint
        uses: ansible/ansible-lint@v6.22.0
```

##### Desired Behavior

agile paradigm should not break backward compatibility ...

##### Actual Behavior

see https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense/actions/runs/7097243220/job/19317040697

**Comment by TehreemNisa** [comment]
This is happening for us as well , is their a workaround available?

**Comment by zerwes** [comment]
my interim fix is to use the latest aka. main instead of a pinned version/tag
see https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense/commit/23b36c914af98ba02b5e565cf37ff63c1c7a13f4

**Comment by McSim85** [comment]
it's weird if I use the specific version: `v6.20.0`
```yaml
name: ansible-lint
on: [pull_request]

jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6.20.0
```
GitHub actions still `wget`s the main branch.

```
Run wget --output-file=.git/ansible-lint-requirements.txt https://raw.githubusercontent.com/ansible/ansible-lint/main/.config/requirements-lock.txt
  wget --output-file=.git/ansible-lint-requirements.txt https://raw.githubusercontent.com/ansible/ansible-lint/main/.config/requirements-lock.txt
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Error: Process completed with exit code 8.
```
Shouldn't it be `v6.20.0` branch?
`https://raw.githubusercontent.com/ansible/ansible-lint/v6.20.0/.config/requirements-lock.txt`
?

**Comment by McSim85** [comment]
I think this was the fix 
https://github.com/ansible/ansible-lint/pull/3762

**Comment by McSim85** [comment]
So, anything before `6.22.1` is broken
https://github.com/ansible/ansible-lint/commit/d7c9bffc5f5e68eafc70e930057fa0c56c4b0a97

**Comment by ajinkyau** [comment]
Fixed as part of #3929

**Comment by zerwes** [comment]
can confirm the fix is working ... at least the workflow will not fail due to the missing requirement file ...
but now it will run against main, independent of the tag / version you configured

```
Run ansible/ansible-lint@v6.22.0
  with:
    setup_python: true
Run wget --output-document=.git/ansible-lint-requirements.txt https://raw.githubusercontent.com/ansible/ansible-lint/main/.config/requirements-lock.txt
...
Building wheels for collected packages: ansible-lint
175
  Building wheel for ansible-lint (pyproject.toml): started
176
  Building wheel for ansible-lint (pyproject.toml): finished with status 'done'
177
  Created wheel for ansible-lint: filename=ansible_lint-6.22.2.dev8-py3-none-any.whl size=297703 
...
ansible-lint 6.22.2.dev8 using ansible-core:2.16.0 ansible-compat:4.1.10 ruamel-yaml:0.18.5 ruamel-yaml-clib:0.2.8
You are using a pre-release version of ansible-lint.
Run ansible-lint
...
```
https://github.com/Rosa-Luxemburgstiftung-Berlin/ansible-opnsense/actions/runs/7114305453/job/19368083185

**Comment by McSim85** [comment]
@zerwes this should be fixed in

https://github.com/ansible/ansible-lint/pull/3762

So, any versions after 6.22.1 should use versioned branch

**Comment by zerwes** [comment]
> So, any versions after 6.22.1 should use versioned branch

good to hear ... the future is saved ... :+1: 
... but what about backward compatibility? "_any versions after 6.22.1_" means for now: no released version :-(
I think #3933 fixes the eval of the var, so it will not fallback to main
