### ISSUE TITLE
github action unable to install requirements

### ISSUE THREAD

**Issue by veksh** [ansible/ansible-lint#3942]
##### Summary

Current github action (6.22.1) behaves as if it is always in "offline" mode (although according to logs it is not) and does not install requirements neigher from `requirements.yml` nor from `galaxy.yml`. This severely limites its usablilty, restricting it to mostly a YAML syntax check.

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

github workflow

##### STEPS TO REPRODUCE

Test case is at <https://github.com/veksh/ans-lint-test>, it is like
- playbook: simple aws s3 upload with the deliberate error in params, like
``` yaml
#...
  tasks:
    - name: Upload data to S3
      community.aws.s3_sync:
        region: "{{ region }}"
        bucket: "{{ bucket_name }}"
        file_root: "{{ data_path }}"
        delete: true
        # will not be detected
        deliberately_broken: true
      register: upload_result
```
- requirements file to install aws collection
``` yaml
collections:
  - name: community.aws
    version: ">=7.0.0"
    type: galaxy
    source: https://galaxy.ansible.com
```
- and github action in `.github/workflows`
``` yaml
# ...
jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6
        with:
          args: "-v"
```
- optionally, `.ansible-lint` config with explicit `offline: false`
```
---
profile: production
offline: false
```
##### Desired Behavior

Flagged error in parameter

```
WARNING  Skipped installing collection dependencies due to running in offline mode.
WARNING  Listing 1 violation(s) that are fatal
args[module]: Unsupported parameters for (basic.py) module: deliberately_broken. Supported parameters include: access_key, aws_ca_bundle, aws_config, bucket, cache_control, debug_botocore_endpoint_logs, delete, endpoint_url, exclude, file_change_strategy, file_root, include, key_prefix, mime_map, mode, permission, profile, region, secret_key, session_token, storage_class, validate_certs (access_token, aws_access_key, aws_access_key_id, aws_endpoint_url, aws_profile, aws_region, aws_secret_access_key, aws_secret_key, aws_security_token, aws_session_token, ec2_access_key, ec2_region, ec2_secret_key, ec2_url, s3_url, security_token). (warning)
```

Local ansible-lint is also reporting that it will not install requirements
```
WARNING  Skipped installing collection dependencies due to running in offline mode.
```
but its ok because they are already installed

##### Actual Behavior

No errors, 3 warnings in logs (first is identical to a normal run of local ansible-lint)
```
WARNING  Skipped installing collection dependencies due to running in offline mode.
INFO     Executing syntax check on playbook upload.yaml (0.42s)
WARNING  Unable to load module community.aws.s3_sync at upload.yaml:13 for options validation
WARNING  Unable to resolve FQCN for module community.aws.s3_sync


```

**Comment by konstruktoid** [comment]
Related: https://github.com/ansible/ansible-lint/issues/3607

**Comment by veksh** [comment]
In case of github action work-around is just to install ansible + lint from system packages (or pip) and run it. 
``` yaml
jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6
        with:
          args: "-v --project-dir ."

      # - name: Install ansible-lint from system packages
      #   run: |
      #     sudo apt update
      #     sudo apt install ansible-core ansible-lint

      - name: Install ansible-lint with pip
        run: |
          sudo apt update
          sudo apt install pip git
          pip install ansible-core ansible-lint

      - name: Run ansible-lint on our repo
        run: |
          ansible-galaxy collection install -r requirements.yml
          ansible-lint -v -s --project-dir .
```
Same result, same time, any version could be used (attemt to use `ansible/ansible-lint@v6.11.0` as an action fails), same way to configure lint (with config file). If action worked, I'd use it, but that's fine too

**Comment by konstruktoid** [comment]
https://github.com/konstruktoid/ansible-cowrie-rootless/actions/runs/8591406635/job/23540136880?pr=183#step:4:7
https://github.com/konstruktoid/ansible-role-hardening/actions/runs/8591453999/job/23540230463?pr=598#step:6:6

related https://github.com/ansible/ansible-lint/issues/3607

`ansible/ansible-lint-action@eb92667e07cc18e1d115ff02e5f07126310cec11` (main branch)
`ghcr.io/ansible/creator-ee:v0.19.0`

**Comment by dbrennand** [comment]
Hey folks, I'm also experiencing the same problems I believe. The `requirements.yml` file located in `ansible/` in my [repo](https://github.com/dbrennand/home-ops/actions/runs/9879441197/job/27285680141) is not being installed by the action prior to `ansible-lint` running.
