### ISSUE TITLE
Not ignoring rules defined in ignore file

### ISSUE THREAD

**Issue by ansiblejunky** [ansible/ansible-lint#3980]
##### Summary

I followed [these steps](https://ansible.readthedocs.io/projects/lint/configuring/#ignoring-rules-for-entire-files) to add a file to ignore, but it only works when I create the root file `.ansible-lint-ignore` but not when I create the `.config/ansible-lint-ignore.txt` file, where I would prefer to have it. ansible-lint doesn't even notice it when its in the config folder.

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
ansible-lint --version
ansible-lint 6.22.1 using ansible-core:2.16.2 ansible-compat:4.1.10 ruamel-yaml:0.18.5 ruamel-yaml-clib:0.2.7
```

- ansible installation method: pip
- ansible-lint installation method: pip

**Comment by gardar** [comment]
Is it a plain directory or a git repo? IIRC the directory needs to be initialized with git for configs to be picked up from the `.config/` dir.
