### ISSUE TITLE
pre-commit hook workaround no longer needed

### ISSUE THREAD

**Issue by dbowling** [ansible/ansible-lint#4005]
##### Summary
The current `pre-commit` hook example references #611 and implements the workaround of `pass_filenames: false`.

That issue is now closed, and this setting can be set to `pass_filenames: true`, which is much faster. The community discussion in the issue seems to point to this being a better default setting.

https://github.com/ansible/ansible-lint/blob/6a8a4025834a1fb49f13d32ae8350fc2550883d0/.pre-commit-hooks.yaml#L10-L13

##### Issue Type

- Bug Report

**Comment by audgirka** [comment]
@dbowling If we pass filenames we will still not be able to get all the results.

**Comment by dbowling** [comment]
Thanks! I was rather confused about this during my initial adoption.
