### ISSUE TITLE
Link to docs page is broken 

### ISSUE THREAD

**Issue by colin-mccarthy** [ansible/ansible-lint#403]
# Issue Type
- Bug report

# Desired Behaviour

ansible-lint/docs/docsite/README.md

Line 3:

`Contains the source behind [docs.ansible.com/lint](https://docs.ansible.com/lint)`

Please fix the link to the docs page, I would have submitted a PR fixing it but was not able to find where it existed online.

# Actual Behaviour (Bug report only)

404 Not Found

**Comment by awcrosby** [comment]
Thanks for the catch, the docsite link was updated and is live at https://docs.ansible.com/ansible-lint
