### ISSUE TITLE
Crash since 24.5.0: 1 MatchError called incorrectly as line numbers start with 1

### ISSUE THREAD

**Issue by nvuillam** [ansible/ansible-lint#4177]
##### Summary

ansible-lint returns the following error
**MatchError called incorrectly as line numbers start with 1**

##### Issue Type

- Bug Report

##### OS / ENVIRONMENT

```console (paste below)
ansible-lint 24.5.0 using ansible-core:2.16.6 ansible-compat:24.5.1 ruamel-yaml:0.18.6 ruamel-yaml-clib:0.2.8
```

- ansible installation method: pip
- ansible-lint installation method: pip

##### STEPS TO REPRODUCE

```console (paste below)
ansible-lint
1 MatchError called incorrectly as line numbers start with 1
```

##### Desired Behavior

No crash :)

##### Actual Behavior

crash with `1 MatchError called incorrectly as line numbers start with 1`

You can see the error in MegaLinter build log: https://github.com/oxsecurity/megalinter/actions/runs/9149776695/job/25153984448?pr=3559

**Comment by ssbarnea** [comment]
@nvuillam Unless you can update the description to include a reproducer, we will need to to close thing bug.

**Comment by nvuillam** [comment]
@ssbarnea the test files are located here (and they are the same for ages :) )

https://github.com/oxsecurity/megalinter/tree/main/.automation/test/ansible/bad/ansible

Does it help ?
