### ISSUE TITLE
Drop support for Ansible < 2.5

### ISSUE THREAD

**Issue by webknjaz** [ansible/ansible-lint#427]
# Issue Type
- Cleanup request

# Desired Behaviour

No shims for vintage Ansible versions in code.

# Actual Behaviour (Bug report only)

There's a ton of conditionals across the code base which facilitate using Ansible Lint with EOL versions of the Ansible Engine (Core).
We've already dropped testing of it from CI and tox envs, now it's time to wipe it away completely.
This is a kind of technical debt which makes the code more complex and harder to maintain.

**Comment by awcrosby** [comment]
I think this would be good
