### ISSUE TITLE
Ansible-Lint rules for deprecations

### ISSUE THREAD

**Issue by getjack** [ansible/ansible-lint#429]
# Issue Type
- Feature request

# Desired Behaviour
Ansible does already warn about deprecation depending on the version you are using for your code but only on run-time. If you are unable to always use the latest ansible version but want to migrate to a newer version it would be nice to have a fast check whether a role/task/playbook would execute in a newer version.

With the latest ansible-lint version it is possible not only to check for rules in this repository (-R flag) but also additional rules (-r flag). I'd suggest to add deprecation lint-rules to this repository in a style that you can check for a specific version of ansible before hand so that the code you are developing is newer outdated.

This will also be very useful in a CI/CD pipeline where it is not possible to have multiple ansible host or where docker images are expensive to handle (e.g. via kitchen-ansible).

Example:
I am using ansible 2.4 and want to upgrade to 2.7.
`ansible-lint -R -r /rules/deprecated`
or
`ansible-lint -R -r /rules/deprecated/2.5 /rules/deprecated/2.6 /rules/deprecated/2.7`

**Comment by ssbarnea** [comment]
Closing as wontfix as our current compatibility matrix does not allow us to do it. Also doing this would create a serious maintenance burden.

The expectation is that user would run the linter using the latest supported version of Ansible, which is not necessarily the same version they would use in production.
