### ISSUE TITLE
ansible-lint --fix scope is harmful

### ISSUE THREAD

**Issue by andrewimeson** [ansible/ansible-lint#4326]
##### Summary

The `--fix` feature dealing with formatting of YAML is scope creep beyond what I want a tool named ansible-lint to do. I don't want ansible-lint linting YAML form (I run yamllint separately so that I can lint non-Ansible files, and have clear separation of tools), but at least I can disable that and it gets out of the way.

I handle YAML auto-formatting with a separate tool (yamlfix or Prettier). I would expect `ansible-lint --fix` to only fix Ansible-specific issues, but it reformats the whole file. I don't even use the feature because it's incompatible with my YAML formatting and linting tools.

Since #4139 and #4158, I have to deal with a warning that I can't suppress because of a feature that has a scope beyond what it should.

Please consider whittling down the feature to remove YAML formatting concerns and instead recommend other tools for that purpose. At a minimum, the warning about incompatible yamllint settings should be suppressible.

##### Issue Type

- Bug Report

**Comment by ssbarnea** [comment]
If you want to limit the scope of ansible-lint, you are welcomed to use its exclude functionality to force it to look only at specific files/folders.

We do not plan to add any functionality that would treat non-ansible files differently when it comes to reformatting.

**Comment by andrewimeson** [comment]
I'm not asking for ansible-lint to treat non-Ansible files differently. I'm asking ansible-lint to stick to linting Ansible, and not give warnings that I can't disable about incompatible yamllint settings when I have the Ansible yamllint integration disabled.

The warning should be able to be disabled, at least.
