### ISSUE TITLE
Can't install a recent version of ansible-lint with uv

### ISSUE THREAD

**Issue by bolinocroustibat** [ansible/ansible-lint#4348]
Environment: MacOS 15.0
Ansible version: 10.4.0
[uv](https://github.com/astral-sh/uv) version: 0.4.15

When trying to installed ansible-lint n a uv-managed virtual environment, with `uv add ansible-lint`, [uv](https://github.com/astral-sh/uv) will only installed the version 6.8.7 which seems to be the last version with a dependency tree that uv can resolve.
So I tried to force a more recent version by specifying the version in `pyproject.toml` (for example `>=24.9.2`), but in that case I get the following dependency tree solving error:
```
  × No solution found when resolving dependencies for split (python_full_version == '3.11.*'):
  ╰─▶ Because will-not-work-on-windows-try-from-wsl-instead{platform_system == 'Windows'}==0.1.0 was yanked (reason: This package should not have
      anything published) and only will-not-work-on-windows-try-from-wsl-instead{platform_system == 'Windows'}==0.1.0 is available, we can conclude that
      all versions of will-not-work-on-windows-try-from-wsl-instead{platform_system == 'Windows'} are incompatible.
      And because ansible-lint==24.9.2 depends on will-not-work-on-windows-try-from-wsl-instead{platform_system == 'Windows'} and only
      ansible-lint<=24.9.2 is available, we can conclude that ansible-lint>=24.9.2 cannot be used.
      And because dotfiles:dev depends on ansible-lint>=24.9.2 and your project depends on dotfiles:dev, we can conclude that your project's requirements
      are unsatisfiable.
```

I also tried the following in the `pyproject.toml`:
```
dependencies = [
    "ansible>=10.4.0",
    "ansible-lint>=24.9.2 ; sys_platform != 'Windows'",
]
```
...but this platform flag seems to have no effect and I get the same error.
```
  × No solution found when resolving dependencies for split (python_full_version == '3.11.*'):
  ╰─▶ Because will-not-work-on-windows-try-from-wsl-instead{platform_system == 'Windows'}==0.1.0 was yanked (reason: This package should not have
      anything published) and only will-not-work-on-windows-try-from-wsl-instead{platform_system == 'Windows'}==0.1.0 is available, we can conclude that
      all versions of will-not-work-on-windows-try-from-wsl-instead{platform_system == 'Windows'} are incompatible.
      And because ansible-lint{sys_platform != 'win32'}==24.9.2 depends on will-not-work-on-windows-try-from-wsl-instead{platform_system == 'Windows'}
      and only ansible-lint{sys_platform != 'win32'}<=24.9.2 is available, we can conclude that ansible-lint{sys_platform != 'win32'}>=24.9.2 is
      incompatible.
      And because dotfiles:dev depends on ansible-lint{sys_platform != 'win32'}>=24.9.2 and your project depends on dotfiles:dev, we can conclude that
      your project's requirements are unsatisfiable.
```

**Comment by bolinocroustibat** [comment]
Update:

... in the meantime, I found a way to bypass this issue, by adding the following to the `pyproject.toml`:

```
[tool.uv]
environments = ["platform_system != 'Windows'"]

```

**Comment by davedittrich** [comment]
This same dependency resolution problem is happening with `poetry` on Mac OS X, which is not a Windows platform. It seems the method of trying to enforce operating system compatibility with an Ansible project via a fake dependency meant to be an error message at install time using `pip` is problematic for the general case.

Could this please be done instead at runtime in the Python code, with a command line option (and config file setting)? This would allow a developer/debugger to ignore the problem when linting to avoid this being a blocker when debugging other dependency issues.

**Comment by dpprdan** [comment]
> It would be great if the limitation with Windows was implemented for standard `pyproject.toml` files, as `"ansible-lint>=24.9.2 ; sys_platform != 'Windows'` is [the PEP standard](https://peps.python.org/pep-0508/).

That seems to be a [`uv` issue](https://github.com/astral-sh/uv/issues/6127).

**Comment by dpprdan** [comment]
AFAIU the issue is as follows:
`uv` is creating a [universal/cross-platform project lockfile](https://docs.astral.sh/uv/concepts/projects/#project-lockfile), i.e. it is trying to resolve a package (in this case `ansible-lint`) for all platforms, so also for Windows. [poetry](https://github.com/ansible/ansible-lint/issues/2730) and [pdm](https://github.com/pdm-project/pdm/issues/1575) essentially do the same. Due to #2712 it is not possible to resolve `ansible-lint>=6.9.0` on Windows, hence the error.

> ```
> [tool.uv]
> environments = ["platform_system != 'Windows'"]
> ```

That is [`uv`'s way](https://docs.astral.sh/uv/reference/settings/#environments) to restrict the environments against which to resolve dependencies. It is probably a good idea to declare it like this for an ansible project anyway. If `"ansible-lint>=24.9.2 ; sys_platform != 'Windows'` were observed by `uv` [as intended](https://peps.python.org/pep-0508/#environment-markers) (see the linked issue above), `uv` would still build the lockfile for Windows as well, just not with ansible-lint. There might be edge-cases where this is useful, but probably not for an average ansible project.

While I find the use of a fake dependency to prohibit the installation on a certain platform not very elegant, I am also puzzled by the fact that apparently (i.e. AFAIK) python does not provide an obvious solution for this (IMHO) reasonable use-case.

**Comment by dpprdan** [comment]
@ssbarnea You're confusing the [uv pip interface](https://docs.astral.sh/uv/getting-started/features/#the-pip-interface)¹ with the [uv project interface](https://docs.astral.sh/uv/getting-started/features/#projects)². The pip interface doesn't use `uv.lock` files.

Steps to reproduce: 

```python
uv init
uv add ansible-lint
uv pip show ansible-lint
``` 

Alternatively `uv add "ansible-lint>=24.9.2"` will trigger the "No solution found" error.

¹ "Manually managing environments and packages — intended to be used in legacy workflows or cases where the high-level commands do not provide enough control."
² "Creating and working on Python projects, i.e., with a `pyproject.toml`"

**Comment by bryanwweber** [comment]
I am also experiencing the same issue as in the OP. The recommendation from @dpprdan to add

```toml
[tool.uv]
environments = ["platform_system != 'Windows'"]
```

to `pyproject.toml`, along with enforcing that `ansible-lint >= 6.16` worked for me.

The real problem that I was experiencing was with an incompatibility of `ansible-lint` with `ansible-compat` from https://github.com/ansible/ansible-lint/issues/3408. `uv` was resolving the `6.8` series of `ansible-lint` which didn't have the Windows package depedendency.

Please, please consider making this a runtime check. As seen in issues related to poetry and pdm, this is not a unique problem and reports of this will continue to come in I expect.

**Comment by MaKaNu** [comment]
@bryanwweber you are right I am getting always 6.8 without a workaround so here is the next report. I admit I did not fully understand why this is happening...

**Comment by connorhsm** [comment]
Continues to be a frustrating issue here too.

With no other dependencies, `uv add ansible-lint` quietly resolves to `v6.8.7`, while the latest version is `v24.12.2`.

This is a very subtle issue, but the impact is a broken development environment that confusingly appears to be other problems, making it tiresome to debug.

The suggested fix also worked for me, when using Linux:
```toml
[tool.uv]
environments = ["platform_system != 'Windows'"]
```

@ssbarnea Is there anything further I can provide to aid in debugging?

**Comment by connorhsm** [comment]
Continues to be a frustrating issue here too.

With no other dependencies, `uv add ansible-lint` quietly resolves to `v6.8.7`, while the latest version is `v24.12.2`.

This is a very subtle issue, but the impact is a broken development environment that confusingly appears to be other problems, making it tiresome to debug.

The suggested fix also worked for me, when using Linux:
```toml
[tool.uv]
environments = ["platform_system != 'Windows'"]
```

@ssbarnea Is there anything further I can provide to aid in debugging, ideally to reduce the impact of this?

Thankfully it appears the uv project is now aware https://github.com/astral-sh/uv/issues/9752

**Comment by bolinocroustibat** [comment]
Still the case here with newer versions of uv, not sure we should keep this closed

**Comment by austinpray-mixpanel** [comment]
Just ran into this

```
uv add --dev 'ansible-lint'
```

Gives me `ansible-lint>=6.8.7` in my pyproject.toml without the workaround

**Comment by MaKaNu** [comment]
Installing ansible via `ansible-dev-tools` resolves in  `ansible-lint==25.8.2`. As far as I understand, the development progress `adt` will be the future of installing ansible.

Somebody correct me, if I am wrong.

**Comment by gtirloni** [comment]
Last time this hack caused problems: https://github.com/ansible/ansible-lint/issues/2816

**Comment by ssbarnea** [comment]
@austinpray-mixpanel If you use an ancient and unsupported version of python, you will get an unsupported version of ansible-lint too.
