### ISSUE TITLE
Unfinished sentence in docs/profiles.md

### ISSUE THREAD

**Issue by aj2s** [ansible/ansible-lint#4358]
##### Summary

> Ansible-lint profiles gradually increase the strictness of rules as your Ansible content lifecycle.

Is it me, or does it seem like this sentence in docs/profiles.md is unfinished? 

Totally guessing how the sentence was meant to end:

- "Ansible-lint profiles gradually increase the strictness of rules **of** your Ansible content lifecycle." ? Even then, I don't know what that means.

- "Ansible-lint profiles gradually increase the strictness of rules as your Ansible content lifecycle **matures**." ? Still unsure, but that sounds like a finished sentence to me

**Comment by cavcrosby** [comment]
I like the second sentence you suggested, though I would probably modify it slightly to say the following.
> Ansible-lint profiles gradually increase the strictness of rules as your Ansible content **matures**.

I'd recommend submitting a PR for the maintainers to take a look.

**Comment by binojmn** [comment]
@cavcrosby , have raised the PR. Please let me know if any other changes needed
