### ISSUE TITLE
The ansible-lint is detecting an issue when it shouldn't (regex to loose)

### ISSUE THREAD

**Issue by elafontaine** [ansible/ansible-lint#485]
https://github.com/ansible/ansible-lint/blob/e44d2aad2aa1a14a1766afad7c33af4afbeb212b/lib/ansiblelint/rules/VariableHasSpacesRule.py#L16

The regex is matching on this line ;
`command: '{{ mongo_cli }} --eval "rs.status().members.forEach(function(member){if(member.stateStr==\\\"PRIMARY\\\"){print(member.name);}});"'
`
It matches the last "}}" inside the mongo eval.  

Is this something you would want to fix?

**Comment by ssbarnea** [comment]
That is likely one of those cases where you just add a inline ignore. I doubt a regex would ever be able to fully parse complex jinja.
