### ISSUE TITLE
Pre-commit link in docsite is broken

### ISSUE THREAD

**Issue by maxwell-k** [ansible/ansible-lint#486]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

The footer on the docsite says: "Last updated on Feb 12, 2019."

This is a documentation bug report - a broken link on the ansible-lint docsite, it does not need ansible or ansible-lint to be installed to experience the bug.

# Desired Behaviour

The link in the [instructions](https://docs.ansible.com/ansible-lint/configuring/configuring.html#pre-commit-setup) for configuring ansible-lint should work the same as the link in the [README](https://github.com/ansible/ansible-lint#pre-commit-setup) and take the user to https://pre-commit.com/  

# Actual Behaviour (Bug report only)

The the instructions instead points back to the same page with `#id4` appended:

https://docs.ansible.com/ansible-lint/configuring/configuring.html#id4

The link also displays incorrectly 

![image](https://user-images.githubusercontent.com/4786215/53876533-e489f400-3ffe-11e9-8bf0-6a6f71c5ccf3.png)

I think this is down to how the reStrucutredText from the README.rst is included in the docsite but I do not yet understand the build system:

https://github.com/ansible/ansible-lint/blob/master/docs/docsite/rst/configuring/configuring.rst

**Comment by webknjaz** [comment]
Thanks for the report!

For the future: `tox -e docs` should build docs for you locally.
