### ISSUE TITLE
jinja2: found character '%' that cannot start any token

### ISSUE THREAD

**Issue by decentral1se** [ansible/ansible-lint#496]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible 2.7.7
  config file = None
  configured module search path = ['/home/decentral1se/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/decentral1se/ansible/molecule/.venv/lib/python3.7/site-packages/ansible
  executable location = /home/decentral1se/ansible/molecule/.venv/bin/ansible
  python version = 3.7.2 (default, Feb 21 2019, 17:48:02) [GCC 6.3.0 20170516]

ansible-lint 4.1.0
```

- ansible installation method: pip
- ansible-lint installation method: pip

# Desired Behaviour

We have a bunch of plays with jinja2 templating in them over in the world of molecule and it would be nice to lint them as is. Is there some way we can make `ansible-lint` skip jinja2 tags? Seems like a generally useful thing since jinja2 is quite widely used.

```
(.venv) ➜  molecule (cifix/implement-further-dep-checks) ✔ find molecule -name "*.yml" | xargs ansible-lint -v                     
Examining molecule/provisioner/ansible/playbooks/docker/destroy.yml of type playbook
Syntax Error while loading YAML.
  found character '%' that cannot start any token

The error appears to have been in '/home/decentral1se/ansible/molecule/molecule/cookiecutter/scenario/verifier/inspec/{{cookiecutter.molecule_directory}}/{{cookiecutter.scenario_name}}/verify.yml': line 6, column 2, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


{% raw -%}
 ^ here

[1]    24078 done       find molecule -name "*.yml" |
       24079 exit 123   xargs ansible-lint -v
```

# Actual Behaviour (Bug report only)

`ansible-lint` can handle skipping jinja templating when passing through plays.

**Comment by decentral1se** [comment]
Any indication on how to handle this? Should it do it automatically or would a CLI flag be more advisable (`--skip-jinja` or whatever)? I'd take a stab at an implementation with some indication that it goes on the right path and would be accepted.

**Comment by decentral1se** [comment]
Won't have time to chase this.

**Comment by chriscroome** [comment]
I just hit the `found character '%' that cannot start any token` error, in my case it was caused by having a template with a `.yml` extension and was [solved](https://git.coop/webarch/debug/commit/c66b167e208fc5e03758b5ef9080a737c7a97c8f) by changing it to a `.yml.j2` extension &mdash; I'm leaving this here in case anyone else hits this problem and then finds this issue.
