### ISSUE TITLE
ansible-lint 4.1.1 must be released ASAP 

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-lint#559]
Last release was back in february and while a fix for E206 bugs was merged we cannot consume it because no tag was added.

The lack of a release is forcing few OpenStack projects from using 2+ years old version of ansible-lint. Some people even considered dropping the use of the tool because it becames unreliable.

PS. Even a pre-release like `4.1.1rc1` would enable us to start consuming it.

**Comment by dnorthup-ums** [comment]
@ssbarnea Would this make it more likely that a recent ansible-lint gets picked up in FC30?

**Comment by ssbarnea** [comment]
@dnorthup-ums Luckly for me I am not in the business of creating rpms for pure python packages. You will always be better off installing wheels than rpms for python.

`4.1.1a0` was released shortly after my message, which can be consumed by anyone if they mention it by name (is considered prerelease -- but works nice!).
