### ISSUE TITLE
[HELP WANTED] [SEND PR] Get rid of the deprecated `imp` module usage

### ISSUE THREAD

**Issue by webknjaz** [ansible/ansible-lint#602]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

N/A

- ansible installation method: tox tests
- ansible-lint installation method: tox tests

# Desired Behaviour

`pytest` should not fail in the strict warning mode (`filterwarnings = error`)

# Actual Behaviour (Bug report only)

`DeprecationWarning` is raised and pytest errors out. To see and fix this, remove the corresponding ignore lines from `pytest.ini`

**Comment by webknjaz** [comment]
@slsh1o do you want to try this one out?

**Comment by slsh1o** [comment]
Yep. I take it.
