### ISSUE TITLE
[HELP WANTED] [SEND PR] Get rid of the deprecated `inspect.getargspec()` function usage

### ISSUE THREAD

**Issue by webknjaz** [ansible/ansible-lint#603]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

N/A

- ansible installation method: tox tests
- ansible-lint installation method: tox tests

# Desired Behaviour

`pytest` should not fail in the strict warning mode (`filterwarnings = error`)

# Actual Behaviour (Bug report only)

`DeprecationWarning` is raised and pytest errors out. To see and fix this, remove the corresponding ignore lines from `pytest.ini`

**Comment by slsh1o** [comment]
I would like to take this one.

**Comment by webknjaz** [comment]
Assigned.
