### ISSUE TITLE
feature: use logging instead of print

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-lint#618]
# Issue Type
- Feature request

# Desired Behaviour

Ansible-lint should avoid using ``print()`` for anything else than rule matches (which are the main output of the tool). 

All informative messages (debug, warnings,....) should be handled via the logging module, which  also correctly uses stderr at its default output.

When this is implemented it would be much easier to set logging level based on verbosity level an d allow us to have various verbosity levels.

**Comment by ssbarnea** [comment]
@awcrosby @webknjaz What do you think about this? I would gladly switch to use stdlib logging instead but I do not want to work on this if is not desired. For this project is should be quite easy as there are not so many calls.

**Comment by webknjaz** [comment]
I fully support using `logging`. We'll need to make sure it works well with formatters, though. So that log messages will only be in stderr and stdout would be clean and ready to be piped into some parser if needed.

**Comment by ssbarnea** [comment]
Fixed last week.
