### ISSUE TITLE
Feature Request: Replace deprecated libraries

### ISSUE THREAD

**Issue by mjtrangoni** [ansible/ansible-lint#635]
Hi,

I was trying `pylint-3` on the master branch, and pylint found one deprecated library and one deprecated method. See,

```bash
$ pylint-3 --disable=missing-docstring,invalid-name $(find . -type f -name "*.py") | grep depre
lib/ansiblelint/utils.py:560:31: W1505: Using deprecated method getargspec() (deprecated-method)
lib/ansiblelint/__main__.py:26:0: W0402: Uses of a deprecated module 'optparse' (deprecated-module)

```

**Comment by webknjaz** [comment]
Feel free to send a PR.

**Comment by evitalis** [comment]
I can take a shot at this if its still available. I didn't see a PR at this time, but doesn't mean someone isn't already working on it.

**Comment by evitalis** [comment]
Sorry for the spam guys, I had to rebase to squash a few commits, guess it didn't reflect here.

#645 should fix the warning for getopt. I deprecated function cannot be fixed while py27 is supported as there is no replacement function until py3.0. Good news is the updated function is a drop in replacement and passes the tox testing for py3.x.

**Comment by webknjaz** [comment]
Removal of `inspect.getargspec()` is tracked @ #603.
