### ISSUE TITLE
4.2.0: TypeError: join() argument must be str or bytes, not 'NoneType'

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-lint#652]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

```
ansible --version

ansible-lint --version
4.2.0
```

- ansible installation method: one of source, pip, OS package
- ansible-lint installation method: one of source, pip, OS package

# Desired Behaviour

Not to crash, passing or with meaningful error.

# Actual Behaviour (Bug report only)

```
  File "/Users/ssbarnea/c/opendev/zuul-jobs/.tox/linters/lib/python3.7/site-packages/ansiblelint/utils.py", line 299, in _rolepath
    path_dwim(basedir, os.path.join('roles', role)),
  File "/Users/ssbarnea/c/opendev/zuul-jobs/.tox/linters/lib/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/Users/ssbarnea/c/opendev/zuul-jobs/.tox/linters/lib/python3.7/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```

## Reproducing

It seems to be caused by use of `incude_role`:
```
- hosts: all
  tasks:
    - name: foo
      include_role:
        role: run-buildset-registry
```

# Workaround

Rename `role` key to `name` and the linter will work fine, name is what official documentation mentions, role key is undocumented, probably there as an alias for compatibility.

**Comment by geerlingguy** [comment]
I hit the same thing in my testing; just used:

```
- include_role: [role name here]
```

And couldn't figure out what was triggering the error until I googled this issue.

Workaround of using the following as @ssbarnea mentioned seems to pass linting:

```
    - name: Include a role
      include_role:
        name: [role name here]
```

**Comment by freedemster** [comment]
I ran into the same error with a simple playbook with one `include_role` instruction.
