### ISSUE TITLE
project is not installable in editable mode

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-lint#653]
We need to be sure that `pip install -e .` works on this project as that is the first action any new contributor will try for testing a PR or his own change.

```
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /Users/ssbarnea/c/os/ansible-lint
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```
That is huge problem because installing a package as editable and testing a change made to it is the first thing any contributor would want to do. 

Out of >50 popular python projects I have cloned locally ansible-lint is the only one where installing as editable is broken. I think that the decision to drop the `setup.py` may have being not the best one.

AFAIK there is no workaround to make editable mode work.

Mainly this bug is a big barrier for project development.

* https://github.com/pypa/pip/issues/6605 locked by pypa

**Comment by ssbarnea** [comment]
^ that was quick and without explanations.

**Comment by webknjaz** [comment]
It has all been weighted-in at the time of the refactoring. It's not needed.

**Comment by webknjaz** [comment]
FTR it should be easy to do `pip install .` (in normal mode) and then set something like `export PYTHONPATH="lib/:$PYTHONPATH".

**Comment by webknjaz** [comment]
resolved
