### ISSUE TITLE
Make it possible to integrate `pytest-xdist`

### ISSUE THREAD

**Issue by webknjaz** [ansible/ansible-lint#678]
# Issue Type
- Bug report

# Ansible and Ansible Lint details

devel/master

# Desired Behaviour

It should be possible to run tests in parallel within pytest using `-n auto` arg when `pytest-xdist` is installed.

# Actual Behaviour (Bug report only)

There's some percentage of the red tests appearing in the parallel mode. I assume that some of the tests use a shared context that causes race conditions. This is what has to be investigated and fixed.

**Comment by ssbarnea** [comment]
Considering that running tests takes ~40s, I doubt that running in parallel would produce any real benefits, maybe quite the opposite from the point of view of how they are displayed.

I propose closing this ticket (cleanup backlog) with the remark that if someone wants to propose it, they are still welcomed.

**Comment by webknjaz** [comment]
Real benefits are:
1) No race conditions and tests depending on some shared state (now they clearly collide)
2) New tests won't slow the whole thing down
3) It's not 40s in GHA. It's 50 + 50 + 95 (because you made test envs sequential). And it's occasionally slower in slow envs like macOS.
