### ISSUE TITLE
Publish official docker image 

### ISSUE THREAD

**Issue by jamielennox** [ansible/ansible-lint#727]
# Issue Type
- Feature request

I would expect all of us are using ansible-lint in a CI capacity. Lots of more modern CI systems will only run jobs in a docker container so that the job can't affect the state of the host. 

It would be great if there was an official ansible-lint image that we could use when running in CI systems rather than build our own.

**Comment by webknjaz** [comment]
Are you prepared to maintain it? If not, use the `Dockerfile` from https://github.com/ansible/ansible-lint-action.

**Comment by webknjaz** [comment]
@ssbarnea IIRC Molecule ships images with ansible-lint, right? We could just point people to use them.

**Comment by jamielennox** [comment]
So if there's another way around it that's useful as well. 

I'm not trying to throw more work on a community with zero capacity, given the action is marked as maintained by 'Ansible by Red Hat` this seems to be an official project, please forgive the mistake.

GitHub actions are really only useful for github, looking at the action it would seem that a layout for this would be to publish an ansible/ansible-lint image, and have the GitHub action base from that with the GitHub specific bits?

Writing the dockerfile for this is trivial, i can PR that if you'd like. The part of this that would take work is getting someone with permission to hook up the CI and publishing.

**Comment by webknjaz** [comment]
> this seems to be an official project

Well, technically it's my experiment. So it's not like it's a RedHat supported product.

If you're up to contributing something there, I'll probably accept it. But keep in mind that I'd like to keep that action small.

OTOH you could just use https://molecule.readthedocs.io/en/latest/installation.html#docker and this probably doesn't require any contributions so it probably "just works".

**Comment by webknjaz** [comment]
Considering this is solved.
