### ISSUE TITLE
[HELP WANTED] [SEND PR] Get rid of the `bin/ansible-lint` script

### ISSUE THREAD

**Issue by webknjaz** [ansible/ansible-lint#748]
##### Summary

It's not used in runtime. I only saw it in `TestCliRolePaths.py`. It should be pretty trivial to replace its usage with something more straightforward

##### Issue Type

- Refactoring suggestion

**Comment by webknjaz** [comment]
@ssbarnea comment here so that I could assign this to you

**Comment by ssbarnea** [comment]
@webknjaz I am working on this. Regarding assignment, on other projects I used invite collaborator in order to allow people to be assigned.

**Comment by webknjaz** [comment]
@ssbarnea I have no such power but we could probably ask @gundalow to figure this out.

**Comment by webknjaz** [comment]
Until then — it'd be great if you could leave one comment in issues that you work on, this way GH allows we to assign you.
