### ISSUE TITLE
auto-detect modules with collection layouts

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-lint#778]
Ansible-lint ability to just work without any extra tuning can be improved by making it automatically define `ANSIBLE_LIBRARY=plugins/modules` when the variable is not already defined.

This would follow the [official collection repository layout](https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html) and make ansible-lint more likely work without extra configuration.

This feature should be enabled only with auto-detection mode because it needs to know what is the repository root location. That is because the tool could be called from any subdirectory and we do expect to give the same kind of results.

When implement this feature should allow people to remove extra code added to files like `tox.ini` or `.pre-commit-config.yaml` that define ANSIBLE_LIBRARY in order to be able perform the linting.

**Comment by ssbarnea** [comment]
@webknjaz While trying to fix this I discovered one problem inside __main__, where I tried to alter ANSIBLE_LIBRARY in order to make it discoverable.

By the time __main__ runs, we already imported ansible and altering it will no longer work. That is happening because we do import from ansiblelint.utils which imports from ansible.

Fixing this is not very easy because we host `initialize_logger()` inside utils, which needs to run ASAP, clearly before our detection code.

**Comment by webknjaz** [comment]
@ssbarnea I think this could be done by splitting the utils.

**Comment by ssbarnea** [comment]
While spliting utils may move us into a good direction it will not be enough to address it.

Mainly we are affected by https://github.com/ansible/ansible/issues/69758 and we need to find a way to config Ansible to rediscover its modules after some ansible module imports already happened.
