### ISSUE TITLE
RuntimeError: Failed to find required 'name' key in include_role

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-lint#780]
##### Summary
Bug found on master code, where ansible-lint may produce an exception like:
```python-traceback
RuntimeError: Failed to find required 'name' key in include_role
```

Feel free to assign but to me.

##### Issue Type

- Bug Report

##### STEPS TO REPRODUCE
```yaml
- hosts: all
  tasks:
    - name: foo
      include_role:
        role: bar
```

##### Desired Behaviour
* No exception raised
* If error occurs the filename must be visible, and if possible even line number. At this moment even when running in debug mode we are unable to find the name of the file.

##### Actual Behaviour
```python-traceback
Traceback (most recent call last):
File "/Users/ssbarnea/.pyenv/versions/3.8.2/bin/ansible-lint", line 11, in <module>
load_entry_point('ansible-lint', 'console_scripts', 'ansible-lint')()
File "/Users/ssbarnea/c/os/ansible-lint/lib/ansiblelint/__main__.py", line 91, in main
matches.extend(runner.run())
File "/Users/ssbarnea/c/os/ansible-lint/lib/ansiblelint/__init__.py", line 278, in run
for child in ansiblelint.utils.find_children(arg, self.playbook_dir):
File "/Users/ssbarnea/c/os/ansible-lint/lib/ansiblelint/utils.py", line 183, in find_children
for child in play_children(basedir, item, playbook[1], playbook_dir):
File "/Users/ssbarnea/c/os/ansible-lint/lib/ansiblelint/utils.py", line 235, in play_children
return delegate_map[k](basedir, k, v, parent_type)
File "/Users/ssbarnea/c/os/ansible-lint/lib/ansiblelint/utils.py", line 264, in _taskshandlers_children
raise RuntimeError(
RuntimeError: Failed to find required 'name' key in include_role
```

**Comment by webknjaz** [comment]
Assuming it's a regression.

**Comment by ssbarnea** [comment]
@webknjaz The same exception happens with 4.2.0 and 4.1.0 so it does not really count as a regression.

**Comment by ssbarnea** [comment]
As a note, while Ansible itself accepts the current syntax, that is not the one documented inside https://docs.ansible.com/ansible/latest/modules/include_role_module.html so I am inclined to say that would be enough to make this failure non-fatal, so the user can fix the syntax to the documented one.

I already raised a PR to implement this but we need to look at it as it requires some additional code refactoring.
