### ISSUE TITLE
proposal: use release-drafter to build draft release notes

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-lint#829]
##### Summary
I would like to propose use of two github apps [release-drafter](https://github.com/marketplace/actions/release-drafter) which can help a lot with maintenance chores.

Please note that this is not a request to change the release process, only to enable the tools that help us "draft" the release notes, mainly by keeping the next release notes in sync with recent merges, w/o asking for contributors to do anything.

There are multiple projects in Ansible using it, notable example https://github.com/ansible-community/molecule/releases -- as seen there the drafter updates the description with information from merged PRs, being able to skip mentioning changes that do not affect the final product, using categories, mentioning contributors.

When the maintainer decides to make a release he can still fine tune the already drafter release notes.

##### Issue Type

- Feature Idea

##### Additional Information

An example config which is used in unmodified form by 10+ projects from ansible-community can be seen at https://github.com/ansible-community/molecule/blob/master/.github/release-drafter.yml -- it is simple and effective. The number of categories is kept low to avoid cluttering with major changes listed on top.

I propose enabling this as experimental without having to update any development/release workflows. Once we have it running for a while we can see if we want to update these (like putting a to github releases pages as a place to read the release notes).

**Comment by webknjaz** [comment]
I don't like relying on PR titles because people don't know how to write commit messages already. It's better to enforce something like towncrier change notes like most of the Python projects do.

**Comment by ssbarnea** [comment]
Implemented.
