### ISSUE TITLE
repair docs publishing process

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible-lint#841]
While we would like to use [RTD to build master docs and PRs](https://github.com/ansible/ansible-lint/issues/839) we still need to update official docs from https://docs.ansible.com/ansible-lint/ 

The Jenkins job that used to publish them disparaged during the last year and these docs are now out of sync with the linter.

Official docs are not even versioned per release (like ansible), so user has no clue if documentation refers to development branch, last release or another one.

In order to achieve this we clearly need help from the docs team. Lets use this ticket to track the work that needs to be done.

**Comment by gundalow** [comment]
What's the ask?

that `https://docs.ansible.com/ansible-lint.*` should redirect to `https://ansible-lint.readthedocs.io/en/latest/`?

Or that we want RTD to publish/copy to https://docs.ansible.com/ansible-lint/?

**Comment by ssbarnea** [comment]
Ideally we should publish docs to `docs.ansible.com/ansible-lint` on all merged changes and have them displayed using the same method as ansible itself.

This means:
```bash
https://docs.ansible.com/ansible-lint/ # redir to latest/
https://docs.ansible.com/ansible-lint/latest/index.html
#                                     ^ our master branch
https://docs.ansible.com/ansible-lint/4.3/index.html
https://docs.ansible.com/ansible-lint/4.2/index.html
```

I do not expect RTD to do any publishing for us, I see them only as a test-tool that allows us to see how the docs will render. 

The good part is that we could start publishing master builds to https://docs.ansible.com/ansible-lint/latest/ until we are confident with how they look and add the redirects later.

We need help from the docs team to add the jobs (on whatever build system they prefer). For start it would even be helpful to know how the build is supposed to run, so we can produce a local site.

Do we have another project where is already works fine?

- galaxy docs are unversioned and published their own site
- tower is not versioned

The only one that is versioned seems to be ansible itself but I am bit afraid to even look into how the docs are build for ansible due to its complexity.

**Comment by webknjaz** [comment]
@acozine any chance you could get us an SSH key for rsyncing the docs to prod?

**Comment by ssbarnea** [comment]
@pabelanger Can Zuul help us with publication of content on docs.ansible.com? Does it already have right jobs/credentials to do this?

**Comment by webknjaz** [comment]
@ssbarnea I don't think Zuul has those creds + we'd need our own anyway

**Comment by pabelanger** [comment]
we don't have access to docs.a.c today from zuul. We'd have to get credentials and ensure we could upload to it. Another option is different site and setup htaccess files to redirect

**Comment by webknjaz** [comment]
@pabelanger we already have a "different site and setup" — https://ansible-lint.rtfd.io.
The problem that we're facing is specifically that it's PITA to get those creds.

**Comment by samccann** [comment]
fwiw we implemented the redirect yesterday, so anyone going to docs.ansible.com/ansible-lint will be redirected to RTDs now.

**Comment by ssbarnea** [comment]
@samccann Thanks!
