### ISSUE TITLE
E106: (Role name {} does not match pattern) should permit a . character for namespace

### ISSUE THREAD

**Issue by nre-ableton** [ansible/ansible-lint#967]
##### Summary

Rule 106 will reject role names which do not meet the regex `^[a-z][a-z0-9_]+$`. Unfortunately, this regex seems to be applied to the role's full name, which also includes the role namespace. For example, `geerlingguy.docker` is a valid role name which ansible-lint 4.3.0 rejects on account of the `.` character.

Ansible's [documentation for developing collections](https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html) makes several references to role names which include namespace delimiters.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details
ansible 2.9.12
ansible-lint 4.3.0

- ansible installation method: pip
- ansible-lint installation method: pip

**Comment by nre-ableton** [comment]
I've created a draft PR to fix this: https://github.com/ansible/ansible-lint/pull/968

If this issue is accepted, then I can clean up and submit this PR.

**Comment by ssbarnea** [comment]
See https://galaxy.ansible.com/docs/contributing/creating_role.html#role-names and you will realise that you cannot use dot in role names. Do not confuse this with where you mention the role to be used, a place where you can use dot, but that is to specify the namespace being used. 

Is not the role itself that has dot in it, is the full-qualified-role-name that can have dots. AFAIK, this works fine and the linter does not complain about using `role: foo.bar`.

**Comment by nre-ableton** [comment]
@ssbarnea Ok, thanks for the clarification!
